### ISSUE TITLE
10 things to do in Emacs

### ISSUE THREAD

**Issue by o-nly** [ILUGD/talks#100]
# Abstract
- 10 things to do in emacs, yes you can also edit text!
  I'd prefer if we can have questions to guide the talk.
  I did a screencast version here: https://www.youtube.com/watch?v=x4Wc0deYh28
        
# Expected Duration
- 1hr

# Track
- Beginner
        
# Pre-requisite
- nil
        
# Resources
-  [[https://www.gnu.org/software/emacs/][Gnu emacs]]
-  [[https://www.emacswiki.org/][EmacsWiki]]
-  [[http://emacsrocks.com/][Emacs Rocks]]

# Slides
-  Live demo in emacs.

# Ten things emacs can do
#### Use shell in emacs
- eshell, shell, ansi-term,
leverage the power of elisp and bash at the same time in eshell.
#### Do package management in emacs
- guix.el(system packages), elpa(emacs packages), install, remove, upgrade, and more.
#### Use git in emacs
- magit, commit messages, file diffs, reverting, branching, pulling.
#### Explore files in Emacs
- dired: make dirs, move files, copy, launch programs etc.
#### View pdfs in emacs
- M-x pdf-tools-install, browse to a pdf file
#### View pictures in emacs
- resizing
#### Browse the www in emacs
- eww: quickly copy text into emacs from pastebin and such.
#### Read email in emacs
- gnus: read your email, read mailing lists.
#### Send email from emacs
- C-x m: stmp-send-mail, write email in org
#### Edit text in emacs
- scratch, open & close buffers, find files, edit as root.
#### Write your favorite language in emacs
- japanese, german, chinese, hindi, tamil
#### Write lisp in emacs
- write emacs extensions for your favorite linux applications.

**Comment by hellozee** [comment]
Nice one

**Comment by hellozee** [comment]
Is this a talk or a workshop?

**Comment by o-nly** [comment]
The intent is to get the audience excited to try new(old) software.

the goal is to get people to install emacs, and try out it's best features even if they don't switch to it.

I would think a workshop will be best to accomplish this, but I haven't prepared. The talk is prepared.

**Comment by hellozee** [comment]
I am labeling this as a workshop then, :yum:

**Comment by o-nly** [comment]
* prepare for workshop on emacs
** Install emacs package
First off you will need [Gnu Emacs][https://gnu.org/s/emacs]. There are several distros of emacs
out there, some of the popular ones are Spacemacs, Doom, maybe Linus
torvalds' UEmacs, and there are many others of the text editor
from 1980s. Some of the reasons why people still love and use it may include:
1. E is Extensible
2. Emacs lisp is a powerful language.
3. Emacs is free software
** install emacs from your distro
- apt install emacs/pacman -S emacs etc.
** add & update quelpa, melpa repos
- add line to your `~/.emacs`
(require 'package)
** install emacs from guix(advanced)
- follow this guide at [binary installation][http://www.gnu.org/software/guix/manual/en/html_node/Binary-Installation.html].
** install emacs and extras
- `guix package -i emacs emacs-guix emacs-helm` etc.
* read about emacs at
- emacswiki.org
- gnu.org/s/emacs
- press C-h i in emacs
- M-x package-list-packages to install extensions

**Comment by o-nly** [comment]
I've since then gone ahead and written an extension for emacs. It's called emacs-shroud or shroud.el.

Shroud is a simple cli password manager which uses gpg in the backend to encrypt your passwords.

Shroud.el is an interface to shroud's functionailty through elisp and emacs.

Source: http://nly.info.tm:9000/emacs/shroud.el
