### ISSUE TITLE
Apache Cassandra - Finding the beauty in the architecture

### ISSUE THREAD

**Issue by cosmologist10** [ILUGD/talks#101]
**Abstract**
    In this fast growing world, where we are dealing with complex data which has multi-level   
    nesting and hierarchies, NoSQL acts as a real saviour . While dealing with situations  
    where we want high throughput instead of latency, Cassandra is first preference. In this 
    meetup, I will be talking about cassandra, it's data modeling, architecture of every      
    operations and why these days it is gaining this much popularity.
 
    Topics :
  
    NoSQL advantages over SQL database
    Types of NoSQL
    Column Datatype
    Apache cassandra and its characteristics
    Cassandra architecture
    Key Features of cassandra
    Node Architecture
    Cassandra query language(CQL)
    CQL data structure
      
**Expected Duration**
    
    20 to 30 minutes

**Track**

     - Intermediate

**Pre-requisite**
   	
    Basic knowledge of Database
        
**Resources**

Blog Link for the talk: https://medium.com/@cosmologist10/apache-cassandra-finding-the-beauty-in-the-architecture-190af9ba632e

**Slides**

https://slides.com/shwetasuman/deck-5#/

**Comment by hellozee** [comment]
Finalised for 6th April Meetup

**Comment by brute4s99** [comment]
"ping"

Would you be available to take up this session on 23rd of November, 2019? We are working on finalizing a venue right now. Please be active in the telegram channel of ILUGD and ping @brute4s99 there to confirm your availability.

**Comment by brute4s99** [comment]
slight change: it's 24th November now.

**Comment by miphilomath** [comment]
Blog Link for the talk: https://medium.com/@cosmologist10/apache-cassandra-finding-the-beauty-in-the-architecture-190af9ba632e
Slides: https://slides.com/shwetasuman/deck-5#/

**Comment by miphilomath** [comment]
Hello @cosmologist10, will you be available to take the session again for our virtual meetup sessions anytime soon after 16th May, 2020? 
We would love to host you again on Jitsi, and like to record the session for the future.

Please check our calendar to know about the available dates, https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

cc: @iayanpahwa

**Comment by cosmologist10** [comment]
Hi, @miphilomath I won't be available during that time. Thanks for considering.

**Comment by miphilomath** [comment]
No worries. Let us know when you are available in future and please propose talk then :)
