### ISSUE TITLE
Getting Started with Raspberry Pi

### ISSUE THREAD

**Issue by hellozee** [ILUGD/talks#103]
**Abstract**
	We teach about how is code put into silicon and setting up raspberry without any peripherals.
        
**Expected Duration**
    2 hours

**Track**
    	- Beginner

**Pre-requisite**
   	A raspberry pi

**Slides**
    https://www.slideshare.net/AyanPahwa1/basics-of-embedded-systems-hardware-architectures

**Comment by iayanpahwa** [comment]
@hellozee link to slides --> https://www.slideshare.net/AyanPahwa1/basics-of-embedded-systems-hardware-architectures

Good to close!
