### ISSUE TITLE
File Formats 101

### ISSUE THREAD

**Issue by nk521** [ILUGD/talks#105]
**Abstract**
Are files really safe? Or Do you think that your files can do something you never expect them to do?
Crafting Files from scratch in assembly and python and finding flaws in the structure and also in the parsers!

**Expected Duration**
    60-75minutes

**Track**
    Between Intermediate and advanced

**Pre-requisite**
   	A bit of memory knowledge and a bit of ASM knowledge (you can read nasm/yasm documentation for this and also python struct library)

**Slides**
    Links to the slides.

**Comment by cocoa1231** [comment]
Hello

Can I get a link to the slides?

**Comment by nk521** [comment]
@cocoa1231 I'll have to find them in backups. Will post the link here IF I find them. (Talking about slides and examples)

**Comment by cocoa1231** [comment]
Sure! Thanks!
