### ISSUE TITLE
Workshop III: Using Python with Raspberry Pi

### ISSUE THREAD

**Issue by mridubhatnagar** [ILUGD/talks#106]
**Abstract**
     Python Basics, Raspberry Pi Introduction.
**Expected Duration**
    Approximate duration of the talk.

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner

**Pre-requisite**
       Raspberry Pi setup.
        
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    https://docs.google.com/presentation/d/1vLm0XR2ekXPkeULoUAoaEcMEETx34ljGh23JVYpO6o0/edit?usp=sharing
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by rajudev** [comment]
This workshop was delivered in the RPi Workshop III. 
Thanks @mridubhatnagar for a great workshop.
