### ISSUE TITLE
Interfacing Sensors with the Raspberry Pi

### ISSUE THREAD

**Issue by arush15june** [ILUGD/talks#108]
**Abstract**
	Interfacing various sensors, servos, ultrasonic sensor etc, with the Raspberry Pi.
**Expected Duration**
    1hr 30min

**Track**
   	- Intermediate

**Pre-requisite**
   	- Raspberry Pi with SSH
        - Sensors, Jumpers, Breadboard
        
**Resources**
    https://gpiozero.readthedocs.io/en/stable/recipes.html

**Slides**
    https://docs.google.com/presentation/d/166A1yxStScGNkE7w9XMF67LCqfC9RxnHtMJ2EH2HHlk/edit?usp=drivesdk
    
---

**Comment by rajudev** [comment]
Was this delivered during the RPi Jam workshops?

**Comment by arush15june** [comment]
Yes, it was part of the 2nd workshop.

**Comment by hellozee** [comment]
Nice, closing this with apt labels
