### ISSUE TITLE
Raspberry Pi workshop II - Communication Over LAN

### ISSUE THREAD

**Issue by alok760** [ILUGD/talks#109]
**Abstract**
	communicating with Raspberry Pi over a local area network.
        covering concepts:
- DHCP Server
- SSH
- SFTP
- Flask and gpiozero

**Expected Duration**
    1.5 hours

**Track**
    	Beginner

**Pre-requisite**
   	Enlist here if there are any pre-requisite for attending the talk.
        
**Resources**
    https://github.com/alok760/raspflask

**Slides**
    http://bit.ly/rpiflask
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by rajudev** [comment]
Delivered in the Raspbery Pi workshop II.
Thanks @alok760 for the workshop.
