### ISSUE TITLE
Intro to GraphQL

### ISSUE THREAD

**Issue by gargakshit** [ILUGD/talks#111]
**Abstract**
Intro to GraphQL and authentication with GraphQL (This is a hands on session)
        
**Expected Duration**
~ 2 hours

**Track**
- Beginner

**Pre-requisite**
Get a laptop with nodejs and your favorite ide if you want to follow along
        
**Resources**
https://typegraphql.ml
https://typeorm.io
https://nodejs.org
https://github.com/microsoft/typescript

**Slides**
WIP :)

**Comment by cocoa1231** [comment]
Can we confirm this talk for 6th April?

**Comment by gargakshit** [comment]
Sure :)
Be sure to cancel the dgraph one

On March 31, 2019 5:21:00 PM GMT+05:30, cocoa1231 <notifications@github.com> wrote:
>Can we confirm this talk for 6th April?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ILUGD/talks/issues/111#issuecomment-478334781

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gargakshit** [comment]
**Delivered**
Closing the issue
