### ISSUE TITLE
Drones

### ISSUE THREAD

**Issue by jiviteshkuk26** [ILUGD/talks#112]
**Abstract**
	This talk will be about Drones  
        The topics that the talk is going to cover are :
         -  What are drones?
         -  Types of drones
         -   Physics behind the flight
         -   Parts required to build one

        
**Expected Duration**
    45 Minutes

**Track**
    	- Beginner

**Pre-requisite**
   	Basic understanding of Newton's law of motion, Brushless motors
        
**Resources**
   https://www.theregister.co.uk/2018/05/16/smallest_ai_drone/
   https://hackernoon.com/quadcopter-physics-explained-468ee44ba40b

**Slides**
https://docs.google.com/presentation/d/1Gdb-FYlXgcMoE7pUW2wq1dCVbPi4TeZ37B2Q4rKTUEo/edit?usp=sharing
---
### Note
The slide is not full ready,will do it by 10 <sup>th</sup>April

**Comment by rajudev** [comment]
This seems interesting. We will soon get in touch for when we can schedule this one
