### ISSUE TITLE
Oh My Zip!

### ISSUE THREAD

**Issue by nk521** [ILUGD/talks#114]
**Abstract**
Finding loopholes in ZIP file structure and breaking a server using ZIPs only.
        
**Expected Duration**
60 minutes

**Track**
Intermediate

**Pre-requisite**
None
        
**Resources**
https://en.wikipedia.org/wiki/Zip_(file_format)
PKZIP APPNOTE.TXT (google it out)

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by iayanpahwa** [comment]
@nk521 Please add slides
