### ISSUE TITLE
Kotlin : Language Our generation deserve

### ISSUE THREAD

**Issue by theLimitBreaker** [ILUGD/talks#115]
**Abstract**
 Kotlin is a cross-platform, statically typed, general-purpose programming language with type inference. 
Topics:
- Why Kotlin came ?
- Brief into to language and benefit
- How Kotlin lets write the clean and readable code easily
- Why kotlin is buzz in companies like Netlix
        
**Expected Duration**
   30 Minutes

**Track**
    	- Beginner

**Pre-requisite**
   	little experience with Java or any other OOPs language
        
**Resources**
    https://kotlinlang.org/

**Slides**
    Links to the slides : To be uploaded

**Comment by iayanpahwa** [comment]
@theLimitBreaker Please upload the slides :)

**Comment by theLimitBreaker** [comment]
Sorry for being late 
Slides : https://docs.google.com/presentation/d/1IoCRx5X9X48nxJ_joft2ysEODRQrh66J37iS0AStS6o/edit?usp=sharing

Code : https://github.com/theLimitBreaker/Kotlin-Bear/tree/master/Kotlin101Demo
