### ISSUE TITLE
Introduction to Archlinux: Life without bloatware

### ISSUE THREAD

**Issue by Hritik14** [ILUGD/talks#118]
**Abstract**
The talk will cover the basics of GPT/MBR ESP followed by a minimal installation of Archlinux and i3 WM.    
The target is to showcase the simplicity and flexibility Archlinux provides.     
    
**Expected Duration**
20 min - Difference and importance of GPT and MBR.
40 min - Step by step guided installation of Archlinux.
20 min - Features of Xorg, WM, DM. Precise difference among them.
30 min - Installation of Xorg followed by a minimal i3 installation.
30 min - Pacman and the AUR. The beauty of Arch.
30 min - Fine tuning the terminal and introduction and features of Zsh.
10 min - Showing off our *nix installations.
**3:00 hrs**

**Track**
   	  - Intermediate
    
**Pre-requisite**
    [Archlinux ISO](https://www.archlinux.org/download/)
    1 GB pen drive
    A decent computer (duh)
    Personal internet connection would be encouraged
    Patience (A lot of)
        
**Resources**
[Installation Guide](https://wiki.archlinux.org/index.php/Installation_guide)
[i3wm](https://i3wm.org/docs/userguide.html)
[zsh](https://wiki.archlinux.org/index.php/Zsh)
freenode#archlinux

**Slides**
Slides will be uploaded after the approval.    

**PS**
The content is highly dense. It can be trimmed on request.

**Comment by iayanpahwa** [comment]
Hi @Hritik14 , Thanks for proposing this talk. Will you be available on 8th June to deliver this one?

**Comment by hellozee** [comment]
@iayanpahwa I guess this will mostly suit an install fest and not regular meetups, :)

**Comment by Hritik14** [comment]
@iayanpahwa   Yes.

**Comment by Hritik14** [comment]
Let me know if this has been scheduled for 8th June a day earlier.

**Comment by Hritik14** [comment]
I'm moving out of Delhi.
