### ISSUE TITLE
BigML API with Python

### ISSUE THREAD

**Issue by shakti4ranjan** [ILUGD/talks#12]
Abstract
This talk provides an introduction to working with Machine Learning Algos with BigML ease using Pyhon with its API.

Expected duration
15 min

Intended audience
Beginners-intermediate

Pre-requisite
Just open to learn and enjoy.

**Comment by shakti4ranjan** [comment]
Abstract
This talk provides an introduction to working with Machine Learning Algos with BigML ease using Pyhon with its API.

Expected duration
15 min

Intended audience
Beginners-intermediate

Pre-requisite
Just open to learn and enjoy.

**Comment by sourabhtk37** [comment]
Can you share links to slides/code?

**Comment by flyharrycopter** [comment]
Move this topic under Python, instead of ILUGD/Linux?

**Comment by sourabhtk37** [comment]
Hey @shakti4ranjan 
Could you please move your talk [here](https://github.com/pydelhi/talks/issues)?

**Comment by sourabhtk37** [comment]
I am not seeing any response from the speaker and therefore closing the issue.
