### ISSUE TITLE
"बाएं से दाएं ऊपर से नीचे" : A python talk

### ISSUE THREAD

**Issue by nk521** [ILUGD/talks#120]
**Abstract**
    How python reads the code? How it runs the code? 
        
**Expected Duration**
    60 minutes

**Track**
    Something in between Intermediate and Advanced

**Pre-requisite**
   Python 3.6+ basic understanding of class, functions, decorators, etc.

**Comment by miphilomath** [comment]
The talk is delivered on June 22, 2019 at IGDTUW. Please share the link to slides of the talk here and close the issue

**Comment by nk521** [comment]
This whole session was a live coding session. So there are no slides.
