### ISSUE TITLE
UX/UI and Getting started with Vector Graphics art

### ISSUE THREAD

**Issue by ruchikabgosain** [ILUGD/talks#122]
**Abstract**
	What UX/UI means for a lay-man and how to get a kick start in Vector Graphics. 
       
**Expected Duration**
         30-40 minutes

**Track**
   	Greater than Beginner and Lesser than Intermediate

**Pre-requisite**
   	An interest in designing, and a basic sense of colors, gradients works! 
        
**Resources**
    www.smashingmagazine.com/2009/03/10-principles-for-readable-web-typography/

**Slides**
    Links to the slides here: https://bit.ly/2Rwbyvl

**Comment by miphilomath** [comment]
The talk is delivered on June 22, 2019. Please share the link to slides and close the issue :)

**Comment by ruchikabgosain** [comment]
hey @miphilomath thanks, done!
