### ISSUE TITLE
Presentation: Introduction to Extended Reality

### ISSUE THREAD

**Issue by itsnikhil** [ILUGD/talks#127]
**Abstract**
    Extended Reality (XR) is coined term for Augmented Reality, Virtual Reality and Mixed Reality. It is an emerging field in Technology i.e. many people dont know the about the difference between them especially the technology used behind it. Also, cool things people have made and its different uses cases.

__Topics include__:
    1. History
    2. The definition and differences
    3. Technology behind
    4. Applications (use cases)
    5. Expected growth and
    6. Challenges
        
**Expected Duration**
    Approximate duration of the talk will be around 30 mins.

**Track**
    Beginner - talk would be a general view on this emerging technology.

**Pre-requisite**
    Nothing besides your kind attention
        
**Resources**
GENERAL:
    1. https://www.coursera.org/learn/xr-introduction
AR:
    2. https://developers.google.com/ar/discover/
    3. https://en.m.wikipedia.org/wiki/Simultaneous_localization_and_mapping
VR:
    4. https://www.vrs.org.uk/virtual-reality/what-is-virtual-reality.html
**Slides**
    Link to PDF will be added after the talk

---

**Comment by hellozee** [comment]
Can you couple that up with some cool demos?

**Comment by itsnikhil** [comment]
> Can you couple that up with some cool demos?

I have some example of demos which i will talk about, if you want i can prepare some live demos

**Comment by hellozee** [comment]
Would you be available for 16th or 17th November? If yes then please do go and show us some demos, :D

**Comment by itsnikhil** [comment]
I have my majors starting from 21 Nov 2019, it would be great if you could schedule it a week early or so

**Comment by hellozee** [comment]
@itsnikhil ouch, we are having our anniversary meetup on 2nd, so won't be able to schedule the next meetup within a week, anyway when are your majors finishing?

**Comment by itsnikhil** [comment]
My majors will be finishing on 5 December 2019

**Comment by hellozee** [comment]
@itsnikhil thanks for informing, we would definitely schedule this up for a december meetup, :smile:

**Comment by iayanpahwa** [comment]
Scheduled for Saturday, 4th April on Jitsi, 2100Hrs.

**Comment by itsnikhil** [comment]
[xr.pdf](https://github.com/ILUGD/talks/files/4431934/xr.pdf)
Thank you for attending 💕
