### ISSUE TITLE
Contributing to FOSS and how git comes into picture!

### ISSUE THREAD

**Issue by miphilomath** [ILUGD/talks#128]
**Abstract**
This will be a non-technical talk, featuring:
* Brief history of open source culture and Linux
* Open Source culture and how it came into picture
* Skills required to start contributing to open source, technical and non-technical
* Ways to contribute to open source
* Brief journey of mine
* Lessons I learnt
* Why is git important and how it can help you to contribute.
        
**Expected Duration**
Not long, approximating it for 20-30 minute

**Track**
Beginner
        
**Resources**
* http://catb.org/~esr/faqs/smart-questions.html
* http://www.shakthimaan.com/downloads/glv/presentations/mailing-list-etiquette.pdf
* https://ericsink.com/vcbe/html/history_of_version_control.html
* https://en.wikipedia.org/wiki/Hackers:_Heroes_of_the_Computer_Revolution#Levy's_description_of_hacker_ethics_and_principles

**Slides**
* https://slides.com/philomath/flossing-the-git

**Comment by Amanrazdan** [comment]
Can the telegram group link be shared again

**Comment by miphilomath** [comment]
https://t.me/joinchat/AmwdvEAc48xN_P0xRaR_7Q
