### ISSUE TITLE
Suggestion: An introduction to the Portage Package Management System

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#13]
**Abstract**
Speaker talks about what Gentoo and Portage are, what the USE flag is, some of it's origins, and how the tree system works.
Some live demos should also be there. And then some common tricks to fix portage when it breaks.

**Expected Duration**
20-30 Minutes

**Intended Audience**
Intermediate-Advanced

**Prerequisite**
Should know what PMSs are, and how to use some of the common ones like apt, or yum, or pacman

**Resources**
Portage wiki: https://wiki.gentoo.org/wiki/Portage
Gentoo USE flags: [Wiki](https://wiki.gentoo.org/wiki/Handbook:PPC/Working/USE) and [List of flags](https://www.gentoo.org/support/use-flags/)

By the way, thanks @sourabhtk37 for the format

**Comment by sourabhtk37** [comment]
I suppose this is request for a talk, right?

**Comment by cocoa1231** [comment]
Yes it is

**Comment by manasb** [comment]
This would be an interesting talk!

**Comment by sourabhtk37** [comment]
Assigned to @hellozee.
Please let us know your availabilty and maybe create a new issue with talk/workshop content. Will be closing this if new one is made.

**Comment by hellozee** [comment]
@sourabhtk37 you can close this one, and assign #72 to me.
