### ISSUE TITLE
Hello Computing - From Bare Metal Silicon to Kernel 

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/talks#131]
**Abstract**

- ISA of a processing unit
- Booting 
- RESET 
- Clock
- Privileges / Exceptions levels 
- Memory
- I/O
- Porting an OS
- Kernel Modules
and much more...
        
**Expected Duration**

- 1+ hour 

**Track**

- Advanced

**Pre-requisite**

Good to know but not required :

- Register level access
- Computing Unit Architectures (x86/64, ARM, PPC, RISC-V etc)
- In depth C Programming
- Assembly knowledge would be good
- Memory Mapping and I/Os
    
A 20 mins session will be on the above mentioned topics so attendees with any skill level can join.
    
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.
- https://codeNsolder.com/about
- https://youtube.com/iAyanPahwa

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by utkarsh2102** [comment]
Hello,  
Kinda stupid but could we have a talk/workshop on/for the pre-requisites as well?

**Comment by iayanpahwa** [comment]
@utkarsh2102 I'll touch upon the pre-requisites, during the talk itself. Come and Join :)
