### ISSUE TITLE
The Linux Filesystem : The World Where Everything is a File

### ISSUE THREAD

**Issue by swarnimarun** [ILUGD/talks#133]
**Abstract**
	Brief and simple understanding of the basic concepts of the Linux Filesystem with emphasis on the practical implications of them.
        Starting with a brief introduction to Linux systems and CLI. 
Moving towards the file system concepts involving it's use in Programming, Containers and Linux in general.

**Expected Duration**
    30 mins.

**Track**
    Complete Beginner to Intermediate level

**Pre-requisite**
   Some experience with Linux
        
**Resources**
    To be added....

**Slides**
    https://slides.com/swarnimarun/everything-is-a-file

**Comment by sourabhtk37** [comment]
Great talk. More content could be fitted in, internals or case studies.

**Comment by hellozee** [comment]
@sourabhtk37 :wink:
