### ISSUE TITLE
Playing games and playing with games

### ISSUE THREAD

**Issue by nk521** [ILUGD/talks#134]
**Abstract**
    Playing with games by changing either their obfuscated files or by reversing their source.
        
**Expected Duration**
    45-60 mins

**Track**
   	Intermediate

**Pre-requisite**
   	Knowledge of basic programming, math and an essence of low level assembly (x86)
        
**Resources**
    idk what to link here to be honest

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by brute4s99** [comment]
"ping"

Would you be available to take up this session on 24th of November, 2019? We are working on finalizing a venue right now. Please be active in the telegram channel of ILUGD and ping @brute4s99 there to confirm your availability.

**Comment by nk521** [comment]
I might not be attending any meetups after Nov

that's why I'm closing this issue.

**Comment by iayanpahwa** [comment]
@nk521 please update link to slides.
