### ISSUE TITLE
Alpine Linux on Phone

### ISSUE THREAD

**Issue by xeon-zolt** [ILUGD/talks#139]
**Abstract**
	
- Go through of porting wiki of postmarket OS
- challenges in porting
- experience-sharing on how I partially completed it
- phone showcase for others to use about the feel of Linux on phone
- a small discussion about Linux for phones (we have yet the Desktop Linux war to win)
- talk about different Linux OS available for mobile phones

**Expected Duration**
    30 mins (can go a little long depends on how interested people are)

**Pre-requisite**
   	if someone wants a hands-on can bring an old android phone (if possible one with custom ROMs)
        
**Resources**
   https://postmarketos.org/
**Slides**
    no slides

**Comment by iayanpahwa** [comment]
@xeon-zolt and @cvam0000 please sync and plan this talk for virtual meetup.
