### ISSUE TITLE
Hands on Docker

### ISSUE THREAD

**Issue by mfrw** [ILUGD/talks#14]
I am planning to give a talk on docker, I have several ideas regarding the same:
1. A black belt talk about docker and a small container runtime is written in go. (mini docker)
2. Just the basics of docker, why where etc etc

Please suggest what would benefit us most.
Cheers

**Comment by sourabhtk37** [comment]
Does this talk includes:
1. Internals
2. Various components and how they play together
3. Hands-on

**Comment by mysticTot** [comment]
There  is an updated issue for this talk. So I'm closing this issue

**Comment by rajudev** [comment]
and I just commented about this issue there. Collision.
