### ISSUE TITLE
Apache Kafka for your Event-Driven Ecosystem

### ISSUE THREAD

**Issue by gabru-md** [ILUGD/talks#140]
**Abstract**
	This session will allow people to understand the importance of Apache Kafka and why Event-Driven systems are really important in the current age of computing and services. Apache Kafka still remains a software that is not widely known in the community. This session will try to get people familiarised with the "ins & outs" of Apache Kafka and how it can be employed in almost every Software Development domain.
        
**Expected Duration**
    40-45 mins

**Track**
   	Beginner Friendly

**Pre-requisite**
   	There aren't any pre-requisite for this session.
Having worked with a messaging system or having some experience in developing software systems will be a big plus!
        
**Resources**
[kafka-ilugd.pdf](https://github.com/ILUGD/talks/files/4112182/kafka-ilugd.pdf)

**Slides**
[kafka-ilugd.pdf](https://github.com/ILUGD/talks/files/4112182/kafka-ilugd.pdf)
    
(This was also presented at the OTS Delhi Day)
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by iayanpahwa** [comment]
Hi @gabru-md can you present this talk online over a Jitsi call?

**Comment by iayanpahwa** [comment]
@gabru-md , Scheduled for Saturday, 11th April @2100Hrs on Jitsi

**Comment by miphilomath** [comment]
The talk is delivered. Link to the YouTube recording [here][https://www.youtube.com/watch?v=bfB7eCThp_I]
