### ISSUE TITLE
Generative art 101

### ISSUE THREAD

**Issue by rasponicc** [ILUGD/talks#141]
**Abstract**
	I will introduce basics of creative coding and generative art. Then we will proceed to do it hands on. At the end the members will be able to create stuff from generative mandalas to animations. (language to use will depend on attendees and their interest. Could be any of JavaScript, Processing or Python)
**Expected Duration**
    30 mins

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner

**Pre-requisite**
   	6th grade mathematics
        
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by iayanpahwa** [comment]
@rasponicc confirming the talk for coming Sunday
