### ISSUE TITLE
Underneath the GPIO pins 

### ISSUE THREAD

**Issue by insaaniManav** [ILUGD/talks#142]
**Abstract**
In this talk I am going to talk about what actually happens underneath  when we  type python commands using the gpio library and how do these pins actually work 
        
**Expected Duration**
    between  45 mins to an hour 

**Track**
   	
    	
        - Intermediate
        

**Pre-requisite**
   	//Enlist here if there are any pre-requisite for attending the talk.
        Will do that soon 
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by miphilomath** [comment]
Hey @insaaniManav , Thanks for proposing the talk. Can you please share little more details for attendees, such as the topics covered and prerequisites for attending?

Once you update, please share your availability for the talk. Please check our calendar to know about the available dates, https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

**Comment by insaaniManav** [comment]
Hey @miphilomath thanks for reaching out , 
I am sorry but  It looks like this page was not updated recently 
This talk has already been given on raspi jam 2020 in February :D

**Comment by insaaniManav** [comment]
Also I will update the slides here very soon. Sorry for the delay
