### ISSUE TITLE
Making Pi Clusters & What to use them for

### ISSUE THREAD

**Issue by jasmeet0915** [ILUGD/talks#144]
**Abstract**
	 Raspberry Pi is often the first choice that comes to mind when building IOT based projects or projects applying intermediate machine learning and computer vision. I say 'intermediate' because machine learning and computer vision projects can be really CPU hungry tasks and a single Pi being a credit card sized computer may not be able to cope with that task. But its small size and extremely cheap prize as compared to desktops and laptops allows the makers to cluster two or more Raspberry Pis together so all of them work together parallely to complete the given task extremely fast and efficiently. So in this talk I will show how the cluster works, how you can build your own Pi Cluster and what you can use them for.
        
**Expected Duration**
    30-45 min

**Track**
   	Intermediate

**Pre-requisite**
   	Enlist here if there are any pre-requisite for attending the talk.
        
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by iayanpahwa** [comment]
@jasmeet0915 add slides please.
