### ISSUE TITLE
Making arduino Boards talk 

### ISSUE THREAD

**Issue by insaaniManav** [ILUGD/talks#147]
**Abstract**
	This talk is mainly going to cover communication protocols and how to make two arduino boards talk both by wired and wireless and wireless means 
        
**Expected Duration**
    30-45 mins

**Track**

     ##   - Intermediate
      

**Pre-requisite**
  Basic Arduino programming and knowledge of communication protocols (recommended)
        
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by iayanpahwa** [comment]
Scheduled for Wednesday, 15th April at 2100Hrs.

**Comment by miphilomath** [comment]
The talk is delivered on 15th April, 2020. Link to the recording, https://www.youtube.com/watch?v=0gcGlBG4jH0
