### ISSUE TITLE
Introduction to Arch Linux

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#15]
**Abstract**
I will start off by explaining what Arch is, it's philosophy, and why you'd ever want to go even within 100 meters of it. Then I'll quickly go through an installation in a Vbox, explore pacman, introduce the AUR, create a pkgbuild live, and then talk about AUR helpers. Finally, a quick 5 minute vanity section, where I just set up a GUI

**Expected Duration**
20-30 Minutes

**Track**
Track 2

**Prerequisite**
The audience should just know basics of *sh. This should be pretty beginner friendly

**Resources**
[Arch Linux](https://www.archlinux.org/)
Arch Wiki for: [Pacman](https://wiki.archlinux.org/index.php/pacman), [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository), [VirtualBox](https://wiki.archlinux.org/index.php/VirtualBox), [AUR Helpers](https://wiki.archlinux.org/index.php/AUR_helpers)

**Slides (still working on them)**
http://slides.com/jatinkaushal/deck

**Comment by akash-47** [comment]
Are you sure about the expected duration ?
