### ISSUE TITLE
Configuring Emacs from scratch

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#151]
![image](https://user-images.githubusercontent.com/2010120/77847631-41dd7e00-71dc-11ea-8812-607877d85456.png)

**Abstract**
	Getting started with Emacs can be a daunting task sometimes. Learning different keyboard shortcuts, learning how to do different tasks that you want in Emacs like file browsing, searching, etc. can be daunting to learn.
This will be a follow  along workshop wherein I would demonstrate to you Emacs configurations from scratch the way you want. I would try to cover the following things briefly through the workshop.
- A very basic introduction to Emacs
- How to do basic stuff like text editing, file browsing, searching etc.
- Getting started with Emacs configurations
- Setting up different modes
- Themes
- Doing stuff other than text editing in Emacs, ( Email, Music etc. ) 
( I'll keep adding or modifying to the above list till the time I am ready to do take the workshop)  
        
**Expected Duration**
120 to 180 minutes

**Track**
   	Beginner

**Pre-requisite**
 It would be really good if you are already familiar with the text editing workflow in Emacs, that would speed up the workshop.
        
**Resources**
1 [GNU Emacs](https://www.gnu.org/software/emacs/)

**Slides**
will add the link to recording or any other notes after the talk

**Preferred Time and mode**
Evening

Our end goal is to configure the Emacs to look something similar like below and while doing it, we would learn a lot of useful stuff along the way. 

![image](https://user-images.githubusercontent.com/2010120/77847601-fe830f80-71db-11ea-85d5-3cf50865a9e8.png)

---

**Comment by iayanpahwa** [comment]
@rajudev  , Scheduled for Sunday, 12th April @1400Hrs on Jitsi

**Comment by miphilomath** [comment]
The workshop is delivered on Jitsi.
Link to YouTube Recording: https://www.youtube.com/watch?v=JxMWNmyY8Aw
