### ISSUE TITLE
Getting up and running with KiCad - Online

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/talks#154]
**Abstract**
KiCad for schematic capture and PCB design 
        
**Expected Duration**
1 hour

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner

**Pre-requisite**
Basics of circuit design
        
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.

**Preferred Time and mode**
    Time(day/evening) online/offline.

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by miphilomath** [comment]
The talk has been delivered. 

Link to the youtube recording for the talk: https://www.youtube.com/watch?v=hkDlTxaxgKE
