### ISSUE TITLE
Introduction to Continuous Integration 

### ISSUE THREAD

**Issue by alok760** [ILUGD/talks#155]
**Abstract**
	- CI/CD concepts
        - Introduction to various tools 
        - setting up Jenkins 
        - making a basic pipeline
        - *bonus* TravisCI ++

**Expected Duration**
    Approximate duration of the talk.
        - 1.5 hours 

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner
        - Intermediate

**Pre-requisite**
   	Enlist here if there are any pre-requisite for attending the talk.
       - basic bash(terminal) commands 
   
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.

**Preferred Time and mode**
    Time(day/evening) online/offline.
   - online

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by rajudev** [comment]
we can do 2nd session after this one on `Continuous integration with Gitlab CI`

**Comment by miphilomath** [comment]
Will you be available to deliver the talk on 2rd May, 2020 @alok760?

**Comment by alok760** [comment]
Yes, you can schedule it.

**Comment by miphilomath** [comment]
Great, scheduled it, check the calendar here, https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

**Comment by miphilomath** [comment]
Delivered on 2nd May, 2020. Link to the recording, https://www.youtube.com/watch?v=qzYT-YG3IBs

@alok760 Can you please update the issue with your slides?
