### ISSUE TITLE
Git AMA session

### ISSUE THREAD

**Issue by AniVerma17** [ILUGD/talks#158]
**Abstract**
- An interactive Q&A session on Git.
- Questions can go from the basic commands to advanced features or quirky tricks.

**Expected Duration**
    30 mins

**Track**
    	- Beginner
        - Intermediate
        - Advanced

**Pre-requisite**
- Basic understanding of Git

**Resources**
- [Git official documentation](https://git-scm.com/doc)
- [Git cheat sheet](https://education.github.com/git-cheat-sheet-education.pdf)

**Slides**
    N. A.

**Preferred Time and mode**
- Time: evening
- Mode: online

**Previous Experience**
- [Android development 101](https://github.com/linuxchixin/talks/issues/48)

**Comment by taskmaster9001** [comment]
looking forward to the AMA session! ^_^

**Comment by miphilomath** [comment]
Delivered on 13th April, 2020. Link to recording: https://www.youtube.com/watch?v=jFjngXh7yew
