### ISSUE TITLE
Ansible Basic

### ISSUE THREAD

**Issue by Manas-kashyap** [ILUGD/talks#159]
**Abstract**
In this session, I will cover the basic of CI & CD as well as which part Ansible help us with. 
Topics would be:- 
1) Jinja Templates
2) Ansible-playbook 
3) Structure of roles and inventory files
        
**Expected Duration**
   1 hour

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner
        - Intermediate
        - Advanced

**Pre-requisite**
   	A smile and Zeal to learn
        
**Resources**
https://www.ansible.com/

**Slides**

**Preferred Time and mode**
    At night around 9 or 10 pm

**Previous Experience**
    If you have given talks before please link that here. If you haven't then don't worry, we would definitely help you.

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by miphilomath** [comment]
Will you be available to deliver the session on 3rd May, 2020 online on Jitsi? @Manas-kashyap

**Comment by Manas-kashyap** [comment]
Yes, I will be available for the session.

**Comment by miphilomath** [comment]
Great. So scheduling the talk for 3rd May, 2020, 2100 IST.

**Comment by miphilomath** [comment]
Delivered on 3rd May, 2020. Link to recording, https://www.youtube.com/watch?v=3E8YWNkt5G8

@Manas-kashyap Can you please update the issue with the slides?
