### ISSUE TITLE
Linux processes.

### ISSUE THREAD

**Issue by akash-47** [ILUGD/talks#16]
This talk will be about linux processes.
The topics covered will be roughly the same as detailed in reference below.

reference : http://tldp.org/LDP/intro-linux/html/chap_04.html

**Comment by sourabhtk37** [comment]
Can we finalise this talk for the next meetup? @akash-47

**Comment by sourabhtk37** [comment]
Great talk @akash-47 . I really enjoyed the talk. :tada: 
Closing this issue.
