### ISSUE TITLE
Coding When Performance Matters

### ISSUE THREAD

**Issue by swarnimarun** [ILUGD/talks#160]
**Abstract**
	All of us probably write code but how do you write code when performance matters. What do you do to make code actually fast. And answer questions like, "Do languages even matter?", "Caring about performance in JS is dumb?" and so on...
        
**Expected Duration**
    60 Minutes

~**Track**
        - Intermediate
        - Advanced~

**Track (edit)**
- Beginners
- Intermediate
Not as advanced as it would have been.

~**Pre-requisite**
  Deep understanding of coding concepts. And that's pretty much it, I will be using C++ but I will also give examples in less related languages as well.~

**Pre-requisite (edit)**
Knowledge of a basic programming language. And it's constructs/types.
        
**Resources**
    Just read up on basics of Complexity Theory, Data structures and stuff.

**Slides**
    WIP - But it will mostly be a workshop kind of session.

**Preferred Time and mode**
    online

**Previous Experience**
    Given talks to ILUGD, MozD and other events and few podcasts and online sessions.

**Comment by swarnimarun** [comment]
#### Topics to be covered:
- Computer systems and their basic design
- Understanding performance and how to test it, setting up microbenchmarks and analysis tools.
- Understanding the scalability of hardware and software performance.
- Learning about some Data Structures that can help increase performance by omission or by use. And explaining what each should be used for with some real-world examples.
- Moving towards language-specific optimizations and learning how to use them well. Using C++ and JS as examples for native language and interpreted JIT-compiled languages respectively.
- Discussion about what it means to be fast or performant. And busting some common myths.
- And probably covering some platform-specific optimizations that your compiler is likely doing for you. Also probably help you write better code by busting some more myths....

#### Track (edit)
- Beginners
- Intermediate
Not as advanced as it would have been.

#### Pre-requisite (edit)
Knowledge of a basic programming language. And it's constructs/types.

**Comment by swarnimarun** [comment]
Slides: https://docs.google.com/presentation/d/1ntm8t4P7ViXOuCcph-1--o3fqMF3RsyNrmzGyaFJEzk/edit?usp=sharing

**Comment by miphilomath** [comment]
Talk delivered on May 6, 2020. Link to the recording, https://www.youtube.com/watch?v=jc6foD_8FRo
