### ISSUE TITLE
REST with peace : A generalized approach on RESTful APIs and web services

### ISSUE THREAD

**Issue by AniVerma17** [ILUGD/talks#161]
**Abstract**
- This session talks about the REST architectural style in a detailed, unbiased and genaralized manner. 
- Starting with the introduction to REST and its principles, it discusses how to design HTTP API endpoints in a RESTful style.
- And finishing with a bit of hands-on using cURL (CLI tool) and Postman.

**Expected Duration**
    45 mins - 1 hr

**Track**
    	- Beginner
        - Intermediate

**Pre-requisite**
   - Basic familiarity with HTTP and webservices
        
**Resources**
   - [What is REST – Learn to create timeless REST APIs](https://restfulapi.net/)

**Slides**
   [REST with peace](https://docs.google.com/presentation/d/1O7fXGEKnycA_H4ViLkdYBX-kD4zivUXyyqZsvEi3O_A/edit?usp=sharing)

**Preferred Time and mode**
    Time: evening
    Mode: online.

**Previous Experience**
   - [Git AMA](https://github.com/ILUGD/talks/issues/158)
   - [Android development 101](https://github.com/linuxchixin/talks/issues/48)

**Contact info**
   - Twitter: [@ani_verma17](https://twitter.com/ani_verma17)
   - Telegram: `@AniVerma17`

**Comment by xeon-zolt** [comment]
@AniVerma17 when can we schedule it?

**Comment by AniVerma17** [comment]
> @AniVerma17 when can we schedule it?

I would be available next weekend for the talk. What say?

**Comment by xeon-zolt** [comment]
cool let's schedule it after the Friday quiz

**Comment by AniVerma17** [comment]
> cool let's schedule it after the Friday quiz

No, not the coming weekend. I meant the weekend of the next week.
