### ISSUE TITLE
Developing with WordPress 101

### ISSUE THREAD

**Issue by thisisayush** [ILUGD/talks#163]
**Abstract**
	This talk will cover creating websites/blogs using the most popular CMS, WordPress. From wordpress.com to Self-Hosted version of WordPress, this talk will guide the participants on how they can set up and manage their own WordPress based website, without paying a penny to WordPress. What are the plugins, themes, and other basic WordPress concepts? It will also cover the basics of cPanel, hosting and optimization. 
       Linking #156 
        
**Expected Duration**
    1-1.5 Hr

**Track**
    Beginner

**Pre-requisite**
   	None, however, to test it in local, any PHP server such as XAMPP and an offline copy of WordPress script is recommended
        
**Resources**
    XAMPP: https://www.apachefriends.org/
    WordPress: https://www.wordpress.org/

**Slides**
   https://bit.ly/wordpress101-thisisayush

**Preferred Time and mode**
    Time(day/evening) 26 April 2020 2200 IST

**Previous Experience**
    Lightning session on Python PEP8 in one PyDelhi meetup

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, OpenOffice, etc. should not have any problems viewing it.

**Comment by thisisayush** [comment]
@miphilomath

**Comment by miphilomath** [comment]
Thanks for taking that up. Since Pydata Delhi has talks scheduled on 26th, we need to reschedule the talk. Can we schedule it on 29th or 30th April?

**Comment by thisisayush** [comment]
Is the next Saturday/Sunday available instead?

**Comment by miphilomath** [comment]
Scheduling it for next Saturday, 9th May, 2020 at 2100 IST.

**Comment by thisisayush** [comment]
Added Slides Link in the description.

**Comment by miphilomath** [comment]
Delivered on May 9, 2020. Link to the recording, https://www.youtube.com/watch?v=Hj6dj-Ncl8s
