### ISSUE TITLE
Bash From Scratch

### ISSUE THREAD

**Issue by GypsyCosmonaut** [ILUGD/talks#166]
Abstract

Bash from scratch

About

Would be covering all aspects of Bash

Pre-requisites

Just you laptop with Linux on it (be it in a virtual machine like vmware or virtualbox or on bare metal)

Level

All Levels

Resources

man bash;

Speaker Bio

DevOps Engineer at Knowlarity

**Comment by miphilomath** [comment]
Hey @GypsyCosmonaut, Thanks for proposing the talk on bash. Can you please share little more details for attendees, such as the topics covered and prerequisites for attending?

Once you update, please share your availability for the talk. Please check our calendar to know about the available dates, https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

**Comment by GypsyCosmonaut** [comment]
@miphilomath , I would be using Bash version 5.0.3, people can make sure they are using at least this version or later.
Also I would expect people to have some prior experience with Linux, because this talk is not about basics of Linux, but about learning and advancing in Bash
As for topics, I would be going over topics straight from the man page of Bash 

As per calendar, I can take 10/16 May for the talk

**Comment by miphilomath** [comment]
Cool, so scheduling it for 10th May, 2100 IST, works?

**Comment by GypsyCosmonaut** [comment]
Fine

**Comment by GypsyCosmonaut** [comment]
It's Hands-On

**Comment by miphilomath** [comment]
Link to recording: https://www.youtube.com/watch?v=-xD1_ay-NyM
