### ISSUE TITLE
Vim | Tmux Intro

### ISSUE THREAD

**Issue by GypsyCosmonaut** [ILUGD/talks#167]
Abstract

Vim | Tmux Intro

About

Introduction to Vim and Tmux

Pre-requisites

Just you laptop with Linux on it (be it in a virtual machine like vmware or virtualbox or on bare metal)

Level

Beginner

Speaker Bio

DevOps Engineer at Knowlarity

**Comment by miphilomath** [comment]
Hey @GypsyCosmonaut, Thanks for proposing the talk on Vim and Tmux. Can you please share little more details for attendees, such as the topics covered and prerequisites for attending?

Once you update, please share your availability for the talk. Please check our calendar to know about the available dates, https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

**Comment by GypsyCosmonaut** [comment]
I would be covering basics of using Vim, Tmux, automating tasks with Tmux
Purpose of the talk is to make people feel more comfortable using Vim and Tmux to improve their workflows.

As per calendar, I can take 10/16 May for the talk

**Comment by miphilomath** [comment]
How about 16th May 2100 IST?

**Comment by GypsyCosmonaut** [comment]
Fine

**Comment by GypsyCosmonaut** [comment]
It's Hands-On

**Comment by miphilomath** [comment]
Delivered on 16th May, 2020. Link to the recording, https://www.youtube.com/watch?v=ISeBdd8orDg
