### ISSUE TITLE
Inkscape for total beginners

### ISSUE THREAD

**Issue by nk521** [ILUGD/talks#168]
**Abstract**
    Vector art but with a opensource tool called [Inkscape](https://inkscape.org/)
        
**Expected Duration**
    60 minutes

**Track**
    Beginner

**Pre-requisite**
    _None_
        
**Resources**
    https://www.inkscape.org

**Slides**
    Links to the slides.

**Preferred Time and mode**
    Online

**Previous Experience**
    I'm a full time graphic designer :D

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by miphilomath** [comment]
Hey @GypsyCosmonaut, Thanks for proposing the talk on Inkscape. I am looking forward to the talk.

Can you please share little more details for attendees, such as the topics covered in the session?

Once you update, please share your availability for the talk. Please check our calendar to know about the available dates, https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

**Comment by nk521** [comment]
More details : 
- Understanding what vector art really is.
- Understanding what inkscape has to offer
  - basic tools
  - mastering bezier pen
  - using path functions
  - other misc things (grouping, clipping, etc.)
  - 
- couple of design examples which people can follow

**Comment by miphilomath** [comment]
Delivered on May 13, 2020. Link to recording, https://www.youtube.com/watch?v=kE9n0q2GJgg
