### ISSUE TITLE
Let's talk soft skills! The edge you need to stay ahead of the competition

### ISSUE THREAD

**Issue by vipulgupta2048** [ILUGD/talks#169]
**Abstract**
@cvam0000 @grlwholifts and @vipulgupta2048 will be sharing their views in a sort of panel discussion + webinar type of meetup where we share tips and tricks of improving on your Linkedin profile 

To be completed. Just saving it for further edits and better followup. Probably not this topic. Can we brainstorm over what would people like to hear the most about?  
        
**Expected Duration**
45 Minutes

**Track**
Beginner

**Pre-requisite**
None
        
**Resources**
None

**Slides**
None

**Preferred Time and mode**
Weekends?

**Previous Experience**
Listing @vipulgupta2048's talk experience - https://github.com/vipulgupta2048/talkswith2048
@cvam0000

**Comment by iayanpahwa** [comment]
@miphilomath we decided Wednesdays for non-tech sessions, so we can schedule it next Wednesday at 2100Hrs IST, Is it fine by you? @vipulgupta2048

**Comment by vipulgupta2048** [comment]
This wednesday? Just confirming :see_no_evil:

**Comment by iayanpahwa** [comment]
No No, 6th May :)

**Comment by miphilomath** [comment]
Hi @vipulgupta2048, thanks for proposing the panel discussion. Since we are scheduled for the next 2 weeks, will you be available for the panel discussion on 20th May, 2020? 

Please check the available dates on our calendar here, https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

cc: @cvam0000 @grlwholifts

**Comment by xeon-zolt** [comment]
@vipulgupta2048 when can we schedule it?

**Comment by vipulgupta2048** [comment]
Can do this week.
What about you all @cvam0000 @grlwholifts

**Comment by insaaniManav** [comment]
Does sunday work ?

**Comment by grlwholifts** [comment]
> Can do this week.
> What about you all @cvam0000 @grlwholifts

Monday onwards!

**Comment by vipulgupta2048** [comment]
Works anyday for me

**Comment by insaaniManav** [comment]
@grlwholifts @cvam0000 will you guys be available ?

**Comment by grlwholifts** [comment]
I will be available from Tuesday next week!

**Comment by miphilomath** [comment]
Closing the issue after acknowledging with @cvam0000
