### ISSUE TITLE
Filters, Sed & Awk

### ISSUE THREAD

**Issue by flyharrycopter** [ILUGD/talks#17]
**Abstract**
Speaker talks about what filters are, explains sed and awk use and internal operations, and finally how to write your own sed & awk scripts. Adopts hands on practical approach to demonstrate how to effectively use these powerful tools.

**Expected Duration**
30 Minutes

**Intended Audience**
Intermediate

**Prerequisite**
Regular Expressions

**Comment by sourabhtk37** [comment]
Can we finalise this talk for the next meetup @flyharrycopter ?

**Comment by flyharrycopter** [comment]
Yes, final.
