### ISSUE TITLE
 SoWrong: Absurd ways to do perfectly normal things in python

### ISSUE THREAD

**Issue by theSage21** [ILUGD/talks#171]
**Abstract**

Doing common things in a roundabout and strange way.
- API servers using only for loops
- Running sql in python without custom model classes / raw strings
- Long running jobs without having celery etc

**Expected Duration**

 30 minutes

**Track**
- Intermediate

**Pre-requisite**
You should know basic python.
        
**Resources**

- [slides](https://docs.google.com/presentation/d/e/2PACX-1vSoFqDfoO-B4a7bmF6DkRUMHY_ze3WjYES7pb1IHvhQXIVIARtSRpc-aBmOHnZz-5goUu6F0Yzb02pb/pub?start=false&loop=false&delayms=3000#slide=id.p)
- [code](https://github.com/theSage21/SoWrong)

**Preferred Time and mode**
evening, online

**Previous Experience**
I'll probably need help.

Originally mentioned at https://github.com/PyJaipur/PyJaipur/issues/11

**Comment by iayanpahwa** [comment]
This sounds like a really interesting talk, looking forward to it. Let us know what help you need :)

**Comment by theSage21** [comment]
I put that there in case there's something I need to do to present this. Maybe slides have to be in a special sharable format or something. Otherwise the talk is set.
