### ISSUE TITLE
Chaos theory basics with Python

### ISSUE THREAD

**Issue by theSage21** [ILUGD/talks#174]
**Abstract**

An introduction to chaos and the Mandelbrot set using Python.

- what is meant by chaos?
- building the classic bifurcation graph
- Mandelbrot set basics
- Mandelbrot with color
- Mandelbrot in 3d

        
**Expected Duration**

40 minutes

**Track**

Intermediate

**Pre-requisite**

Basic Python or basic programming knowledge in any language
        
**Resources**

https://github.com/theSage21/mandle

**Preferred Time and mode**
 
Evening online

**Previous Experience**

I've given talks here and there.

**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [x] Share the slides, code snippets and other material used during the talk
 - [x] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [x] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by xeon-zolt** [comment]
lets keep it on saturday at 9pm 
@miphilomath can you share with me the todo of scheduling it

**Comment by insaaniManav** [comment]
The  same has  been  scheduled in the calendar

**Comment by xeon-zolt** [comment]
@theSage21 can you add resource like blog or slides you used

**Comment by theSage21** [comment]
I added stuff to the repo for this talk. https://github.com/theSage21/mandle
