### ISSUE TITLE
Intro to Jetpack Compose

### ISSUE THREAD

**Issue by nikit19** [ILUGD/talks#176]
**Abstract**
Jetpack Compose simplifies and accelerates UI development on Android. In this talk we will understand how can we get started with Jetpack Compose and how different components  in Jetpack Compose works.
        
**Expected Duration**
30 minutes
**Track**
    	- Beginner

**Pre-requisite**
   	Basics of Kotlin or Android development
        
**Resources**
    [Official docs](https://developer.android.com/jetpack/compose)
[Series of blogs written by me](https://proandroiddev.com/how-to-make-a-recyclerview-in-jetpack-compose-fd54417d8479
)
**Slides**
    Links to the slides.

**Preferred Time and mode**
    Any time/ online

**Previous Experience**
I have given few talks before

**Contact info**
   https://twitter.com/NikitBhandari

**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [X] Share the slides, code snippets and other material used during the talk
 - [X] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [X] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by xeon-zolt** [comment]
@nikit19 sheduled for 28th June (Sunday)
I will discuss about timings once they are decided.
