### ISSUE TITLE
A walk through lambda calculus

### ISSUE THREAD

**Issue by theSage21** [ILUGD/talks#177]
**Abstract**

- This talk was originally done by David Beazley.
- We could do a workshop series on this with 1 hour a day for 3 days.
- We start with defining True/False as functions and then slowly building our way up to the Y combinator.
        
**Expected Duration**

3-4 hours

**Track**
   	ILUG-D talks are divided intro three tracks:
        - Intermediate

**Pre-requisite**

You should know python function definitions.
        
**Resources**
https://www.arjoonn.com/kalpana.html

**Preferred Time and mode**
    Fri-Sat-Sun would be great. 

**Previous Experience**

I've given talks before here and there.

**Contact info**

`@arjoonn` on telegram.

**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [x] Share the slides, code snippets and other material used during the talk
 - [x] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [x] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by theSage21** [comment]
https://www.youtube.com/watch?v=pkCLMl0e_0k

**Comment by xeon-zolt** [comment]
when can we have this ?

**Comment by theSage21** [comment]
Whenever you want. I'll need one weekend day before the scheduled date to prepare the talk.

Last time this was discussed we figured that we'll reduce it to one hour.

**Comment by rachejazz** [comment]
@theSage21 hey! How about we have this coming weekend? You can have Sunday as a prep day
If your talk has been delivered, do notify :)

**Comment by theSage21** [comment]
@rachejazz Sadly I don't think I'll have the time to pick this up any time soon. I'm closing out this issue due to this reason.
