### ISSUE TITLE
A look into emulators

### ISSUE THREAD

**Issue by kishore-ganesh** [ILUGD/talks#178]
**Abstract**

The talk is basically going to look behind what emulators are, the different kinds of emulation (high level and low level), and what goes into a typical emulator.

Topics:

1. What is an emulator?
2. A refresher: a high level look at how a CPU works
3. What is high level emulation, and what is low level emulation
4. High level units of an emulator
5. How various parts of a system's intricacies are captured in code
6. Challenges you may encounter when developing an emulator, and how to resolve them (along with some mistakes I had made)

        
**Expected Duration**
  45 minutes? (I'm not sure how to gauge duration)

**Track**
     Intermediate

**Pre-requisite**
   	Need to know a bit about how CPUs work and some basics of assembly instructions
        
**Resources**
I had referred to [this article](http://www.multigesture.net/articles/how-to-write-an-emulator-chip-8-interpreter/):  to understand how an emulator works and to make my first emulator.

**Slides**
  

**Preferred Time and mode**
   Any time is okay.

**Previous Experience**
   First time giving a talk. I don't have any previous experience with this.

**Contact info**
@kishoreganesh on Telegram

**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [x] Share the slides, code snippets and other material used during the talk
 - [x] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [x] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by xeon-zolt** [comment]
http://youtu.be/DwWGPswFTQc

**Comment by xeon-zolt** [comment]
@kishore-ganesh if you can add your slides and other links discussed during the talk

**Comment by kishore-ganesh** [comment]
Link to slides: [bit.ly/emulatorstalk-kishoreganesh](url)
Other Links:
Reverse Engineering the MOS 6502: [https://bit.ly/3jtSIBL](url)
Visual6502: [https://bit.ly/3lHiXGW](url)
One man's quest to build accurate SNES Emulator: [https://bit.ly/31Hb3p1](url)
Reverse emulating the NES: [https://bit.ly/2ESu3HS](url)
