### ISSUE TITLE
Self hosting and Moving away from proprietary SaaSS

### ISSUE THREAD

**Issue by insaaniManav** [ILUGD/talks#179]
**Abstract**
This talk is going to be about self hosting and moving away from proprietary SaaSS
        
**Expected Duration**
    45  

**Track**
    - Beginner

**Pre-requisite**
        None
**Resources**

**Slides**
Coming soon 
**Preferred Time and mode**
    evening / Online

**Previous Experience**
Have given a couple of talks before
**Contact info**
@insaanimanav on Telegram and @insaanimanav:matrix.manav.co.in on matrix 
**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [ x ] Share the slides, code snippets and other material used during the talk
 - [ x ] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [ x ] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by iayanpahwa** [comment]
Talk has been successfully delivered. Recoding can be found here --> https://youtu.be/upTUbArXwGg

Closing this issue, cc : @rachejazz

**Comment by rachejazz** [comment]
@iayanpahwa i hope the other opened ones aren't delivered yet.

**Comment by insaaniManav** [comment]
If we are having a series of talks I would like to request for this talk to be conducted again since the youtube recording is not good. Sometimes my video gets frozen , Sometimes you can't see my PPT etc.
