### ISSUE TITLE
Introduction to GoLang

### ISSUE THREAD

**Issue by mfrw** [ILUGD/talks#181]
**Abstract**
	A very high level introduction to Go
        
**Expected Duration**
    30-45mins

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner

**Pre-requisite**
   	Basics of programming
        
**Resources**
    https://gobyexample.com/

**Slides**
    N/A

**Preferred Time and mode**
    Evening/Online

**Previous Experience**
    Yes.

**Contact info**
    twitter.com/vimfrw

**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [x] Share the slides, code snippets and other material used during the talk
 - [x] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [x] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by iayanpahwa** [comment]
Scheduled this talk for 14th August 2021

Recording and Streaming and Uploading - @chiragshukhla
Host - @iayanpahwa 
Poster / thumbnail - @nk521 
SPAM - mill baat ke

**Comment by ChiragSukhala** [comment]
> Recording and Streaming and Uploading - @chiragshukhla

Sukhala!

**Comment by ChiragSukhala** [comment]
Change label to done, close the issue. @iayanpahwa

**Comment by iayanpahwa** [comment]
@ChiragSukhala add links to slides and video first

**Comment by mfrw** [comment]
Repository for slides/code: https://github.com/mfrw/talks/tree/master/golang-intro
Please install `present` tool from `golang.org/x/tools/cmd/present` to view.

Question: Do i need to upload PDF ? (i can do that as well)

**Comment by iayanpahwa** [comment]
@mfrw it would be great to have a pdf version

**Comment by mfrw** [comment]
Unfortunately conversion to pdf is a little ugly (apologies in advance)
[golang-intro.pdf](https://github.com/ILUGD/talks/files/7088825/golang-intro.pdf)

**Comment by nk521** [comment]
This session is uploaded on YouTube - https://www.youtube.com/watch?v=5RyOlixS2tQ
