### ISSUE TITLE
AMA Request : Data Privacy laws in India and things to keep in mind as a netizen

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/talks#183]
@AniVerma17 @nk521 

**Abstract**
	Provide a brief introduction about the talk.
    Also list the topics that the talk is going to cover.
        
**Expected Duration**
    Approximate duration of the talk.

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner
        - Intermediate
        - Advanced

**Pre-requisite**
   	Enlist here if there are any pre-requisite for attending the talk.
        
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.

**Preferred Time and mode**
    Time(day/evening) online/offline.

**Previous Experience**
    If you have given talks before please link that here. If you haven't then don't worry, we would definitely help you.

**Contact info**
    Add your Telegram/Twitter/LinkedIn handle(s) here, so that meetup organizers can contact you for confirming timings etc.

**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [ ] Share the slides, code snippets and other material used during the talk
 - [ ] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [ ] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by AniVerma17** [comment]
@nk521 can you ask in your contacts to see if someone among them can give their time to conduct this session?

**Comment by ApurvaS16** [comment]
Hi Ayan, happy to help with data privacy laws.

**Comment by iayanpahwa** [comment]
That’s great @ApurvaS16 , we’re thinking of a short session on Data Privacy laws in India, around the world, followed by a Ask-Me-Anything interactive session. Let me know your thoughts :)

**Comment by AniVerma17** [comment]
@ApurvaS16 do open an issue here for the session if you intend to take it. I guess we can then schedule it for the next month.

**Comment by AniVerma17** [comment]
@ApurvaS16 when are you available to take this session? We'll schedule it accordingly.

**Comment by ApurvaS16** [comment]
Hey Animesh, how about tomorrow at 12 PM? Can we jump on a call to discuss
the modalities of the session?

**Comment by ApurvaS16** [comment]
P.S.- Raju, Ayan and Nikhil have my contact number.

**Comment by AniVerma17** [comment]
> Hey Animesh, how about tomorrow at 12 PM? Can we jump on a call to discuss the modalities of the session?

Not possible at 12 PM, but I'll be available after 7 PM. How about then?

**Comment by ApurvaS16** [comment]
Alright!

To clarify, we're jumping on a call at 7 or having the session at 7?

**Comment by AniVerma17** [comment]
> Alright!
> 
> To clarify, we're jumping on a call at 7 or having the session at 7?

Just for the call to discuss about the modalities of the session. After that, we'll schedule the session as per your availability.

**Comment by AniVerma17** [comment]
Okay, scheduling this session on **October 9, 2021** at **2100 hrs IST**.

**Comment by iayanpahwa** [comment]
@AniVerma17 @xeon-zolt @miphilomath let’s add this to ILUG-D shared calendar

**Comment by AniVerma17** [comment]
> @AniVerma17 @xeon-zolt @miphilomath let’s add this to ILUG-D shared calendar

@iayanpahwa yeah, add this.

**Comment by iayanpahwa** [comment]
Done - https://calendar.google.com/event?action=TEMPLATE&tmeid=MmhtNXEyNm9qOWZuYmRtZGk3OXNiZjVhcW8gZm5tbm5tZWt2dGZqOTg2dHNlMmlsMGFsNTBAZw&tmsrc=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com
