### ISSUE TITLE
Bash 101: 🐚 

### ISSUE THREAD

**Issue by pulsar17** [ILUGD/talks#187]
**Abstract**
This will be an introduction to Bash - the *bourne again shell*. I will try to cover the following topics:
- What is a shell?
- A little bit of history about shells
- Bash as the default shell on most distributions
- Some useful tips and tricks that I've gathered over time
        
**Expected Duration**
    30 mins

**Track**
    	- Beginner

**Pre-requisite**
   	Curiosity :)
        
**Resources**
    [BashGuide](https://mywiki.wooledge.org/BashGuide) *[optional to read, but it's a well written guide]*

**Slides**
    WIP. Will update here once finished.

**Preferred Time and mode**
    Offline - Any time is fine.

**Previous Experience**
  [Talks](https://github.com/pydelhi/talks/issues?q=is%3Aclosed+author%3Apulsar17) given @PyDelhi

**Contact info**
  - [Personal Blog](https://pulsar17.me)
  - git{[Hub](https://github.com/pulsar17), [Lab](https://gitlab.com/pulsar17)}
  - pulsar17 on Telegram
  - [@pulsar17](https://mastodon.social/@pulsar17) on Mastodon
  - [@realpulsar17](https://twitter.com/realpulsar17) on Twitter  

**Checklist**

 The talk/workshop speaker agrees to,
 - [x] Share the slides, code snippets and other material used during the talk
 - [x] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [x] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

**Comment by miphilomath** [comment]
@pulsar17 Can we schedule this talk for our January'2023 meetup?

**Comment by pulsar17** [comment]
> @pulsar17 Can we schedule this talk for our January'2023 meetup?

Sure @miphilomath

**Comment by pulsar17** [comment]
Closing this issue, I gave this in January last year ^^
