### ISSUE TITLE
Haskell 101

### ISSUE THREAD

**Issue by ajnsit** [ILUGD/talks#19]
**Abstract**
	Haskell 101 - Absolute beginners introduction to Haskell.
        
**Expected Duration**
    1 Hr

**Track**
   	Beginner

**Pre-requisite**
   	Some programming experience with any language
        
**Resources**
    [Learn You A Haskell](http://learnyouahaskell.com/chapters) might be a good place to learn Haskell. However I would not be using this in the talk itself.

**Slides**
    None yet.

**Comment by sourabhtk37** [comment]
Thanks for the proposal @ajnsit

**Comment by ajnsit** [comment]
I just uploaded the slides here! - https://speakerdeck.com/ajnsit/haskell-101
