### ISSUE TITLE
How not to implement BLE based communication in production

### ISSUE THREAD

**Issue by nk521** [ILUGD/talks#191]
**Abstract**
BLE devices are everywhere and it is secure by default. But people make communication logic based errors. I will be going a service available publicly and how it fails to do BLE communication properly. 
Note: This talk won't a prepared talk. Everything will be improvised.

What will be covered?
1. BLE (ofc)
2. Android reverse engineering nuggets
3. Frida (some bits)
4. Python and BLE
        
**Expected Duration**
    30 minutes - 45 minutes

**Track**
        - Advanced

**Pre-requisite**
   	Bring your brain.
        
**Resources**
    None for now. If I have some time in coming days then I'll put together a blog and paste the link here.

**Slides**
    None. Won't be published.

**Preferred Time and mode**
    Offline

**Contact info**
    `@whotooknikhil` on Telegram. I prefer to talk over mail: `nk_mason@protonmail.com`.

**Checklist**

 Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

 The talk/workshop speaker agrees to,
 - [ ] Share the slides, code snippets and other material used during the talk
 - [ ] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
 - [ ] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by AYAN-AMBESH** [comment]
@nk521  Are you available on 6th April
