### ISSUE TITLE
Linux From Scratch part 1

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#20]
**Abstract**
This session will contain an introduction to the concept of Linux from scratch, along with covering everything till chapter 4 or 5
        
**Expected Duration**
37.5 ± 7.5 minutes

**Track**
Between Beginner and Intermediate

**Pre-requisite**
You shouldn't need any pre requisites apart from knowing what Linux is and the GNU philosophy
        
**Resources**
We'll be covering the LFS book, and the code that will be used is in [this] (https://www.github.com/cocoa1231/lfs) repository

**Slides**
Here: http://slides.com/jatinkaushal/deck-2

**Comment by sourabhtk37** [comment]
Thanks for the great talk @cocoa1231 
hoping to see the hands-on sessions and further chapters.
Closing this issue.
