### ISSUE TITLE
Nftables vs Iptables : Why you should use nftables over iptables?

### ISSUE THREAD

**Issue by mysticTot** [ILUGD/talks#21]
**Abstract**
	Nftables is new packet classification firewalling software. It replaces the popular {ip,ip6,arp,eb}tables.
The agenda of this talk would be to compare iptables and nftables and discussion on nftables benchmarks
**Expected Duration**
1 hour

**Track**
      - Intermediate
       

**Pre-requisite**
   one should be Familiar with basic networking.
        
**Resources**
wiki.nftables.org    
https://developers.redhat.com/blog/2017/04/11/benchmarking-nftables/

**Slides**
No slides yet.

**Comment by sourabhtk37** [comment]
Can we see hands-on working demo in the next meet-up? @mysticTot

**Comment by mysticTot** [comment]
Sure
But,  it won't be official.

**Comment by sourabhtk37** [comment]
Why won't it be officially, we didn't get to see the demo due to kernal compatibilty.

**Comment by sourabhtk37** [comment]
Will we see this talk's hands-on session on next meetup?

**Comment by sourabhtk37** [comment]
Can I close this issue as the talk is delivered? Can you create another issue when you want to give hands-on session on netfilters?

**Comment by mysticTot** [comment]
No slides. I'm closing it
