### ISSUE TITLE
Haskell Absolute Beginner's Tutorial Series - 1

### ISSUE THREAD

**Issue by ajnsit** [ILUGD/talks#23]
**Abstract**
	This is part 1 of an absolute beginner's tutorial series for Haskell / Functional Programming. This part will be a hands-on deep dive into computing using pure functions and abstraction.
        
**Expected Duration**
    1 Hour

**Track**
   	Beginner

**Pre-requisite**
   	Some programming experience in any language (not necessarily functional). It would help, but it's not a prerequisite, if you had also attended the Haskell talk in the meetup on July 1.
        
**Resources**
    None

**Slides**
    None yet.

**Comment by rajudev** [comment]
This one is for the upcoming meetup on  Saturda, 29 July. Right?

**Comment by sourabhtk37** [comment]
@ajnsit Will you be available on 25th Nov for this talk?

**Comment by ajnsit** [comment]
@sourabhtk37 Not this week. I can be available in Dec.

**Comment by sourabhtk37** [comment]
Lining up your talk for 16th Dec then.

**Comment by sourabhtk37** [comment]
May I finalise your talk for 16th of December? @ajnsit

**Comment by sourabhtk37** [comment]
@ajnsit update?

**Comment by ajnsit** [comment]
@sourabhtk37 Where and when is the meetup being held?

**Comment by sourabhtk37** [comment]
16th of December. Most probably CP.

**Comment by sourabhtk37** [comment]
@ajnsit Next meetup is on 6th and at Fueled Noida. Are you available for this talk?

**Comment by ajnsit** [comment]
@sourabhtk37 Unfortunately, I'm not available this week.

**Comment by sourabhtk37** [comment]
Moving this talk to February meetup lineup.

**Comment by sourabhtk37** [comment]
@ajnsit Pls let us know if you would be able to give this talk on 12th of May? Location will most probably be Srijan Tech, CP, Delhi

**Comment by ajnsit** [comment]
Yeah sure I can take this session on the 12th.

**Comment by sourabhtk37** [comment]
Finalising your talk then

**Comment by sourabhtk37** [comment]
https://www.meetup.com/ilugdelhi/events/rjnzmpyxhbqb/

Schedule and venue is updated here. I would recommend to try out your setup with projector before the workshop for smooth sailing.

**Comment by sourabhtk37** [comment]
@ajnsit Thanks for the talk. Looking forward for more.
