### ISSUE TITLE
Debian 9 Stretch Release Party 

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#24]
**Abstract**
A party to celebrate the release of our beloved operating system Debian. 
Lets celebrate the arrival of Debian 9 Stretch. 

**Description**
        Debian [9.0](https://www.debian.org/News/2017/20170617) was released on June 17th, 2017 
It took over 26 months for the transition from Debian 8.0 Jessie to to get to Stretch. 
To celebrate this release a lot of Debian release [parties](https://wiki.debian.org/ReleasePartyStretch) are being organized all over the world. 

As of now. 12 release parties have already been scheduled in India, but most of them in the South and East Indian regions. Why should the North stay behind?
Lets celebrate the release of our beloved operating system. 

**Agenda for the Release Party**

• (Re)Introduction to the Debian Project. (20 min)
• "Why Debian?" (10 min)
• Cake cutting / eating(10 min)
• Debian Install Fest (After the release party side by side to the meetup)
• Distribution of Debian stickers/DVDs/swags etc. 

**Things to bring for the party:** 
If you want to get Debian installed on your systems, bring up your laptops. 

**Expected Duration**
90 mins to 120 mins. 

       

Link to the slides I used to introduce people to the Debian Project. 
[Debian Jessie](https://www.slideshare.net/helioloureiro/debian-jessie)
Originaly created by [Helio Louriero]( http://helio.loureiro.eng.br/ )
And I showed some of the content from [Debian Wiki](wiki.debian.org)

**Resources**

- To know more about the current Debian [Release](https://www.debian.org/News/2017/20170617)

- List of release [parties](https://wiki.debian.org/ReleasePartyStretch) being organized all over the world.

**Comment by mysticTot** [comment]
Please add a link to your slides

**Comment by akash-47** [comment]
Closing this as the talk has been delivered.
