### ISSUE TITLE
How command line parameters are parsed 

### ISSUE THREAD

**Issue by sourabhtk37** [ILUGD/talks#25]
**Abstract**
	This talks will be about a particular abstraction as to how command line parameters while executing a program passed from the shell to the program.  
        
**Expected Duration**
    20-30min

**Track**
Beginner
        
**Pre-requisite**
   	None.
        
**Resources**
   https://blog.stangroome.com/2014/11/09/command-line-parsing-in-windows-and-linux/
   http://daviddeley.com/autohotkey/parameters/parameters.htm
   https://www.gnu.org/software/bash/manual/bashref.html

**Slides**
    https://slides.com/tksourabh/how-command/

**Comment by mysticTot** [comment]
Please share the slides of your talk

**Comment by sourabhtk37** [comment]
Already did. Also made a PR to be added to talks-log.

**Comment by mysticTot** [comment]
Thanks Tk.

**Comment by akash-47** [comment]
Talk has been delivered. Closing the issue.
