### ISSUE TITLE
Hands-on Arduino and a peek at Raspberry Pi

### ISSUE THREAD

**Issue by lbsrex** [ILUGD/talks#32]
**Abstract**
	A Hands-on workshop on Arduino, and talk on Introduction to Raspberry Pi. 
    Arduino:
        1. Do the 'duino
        2. Working with LED
        3. Working with Servo Motors
        4. Working with Motor Drivers and PWM
        5. Working with Serial
        6. Mini Project : Serial Text to Morse on LED.
    Raspberry Pi:
        1. WTF is a RaspberryPi
        2. How do I get this thing to work
        3. Booting the Pi
**Expected Duration**
    60 to 75 minutes.

**Track**
    	- Beginner

**Pre-requisite**
   	Be There. Probably own a laptop (which you have to bring).
        
**Resources**
        https://www.raspberrypi.org/
        https://www.arduino.cc/

**Comment by rajudev** [comment]
Should we expect people to bring Arduino's or raspberry Pi's of there own if they can?

**Comment by lbsrex** [comment]
Yes, that would most certainly be a good idea.

_Sent from my Motorola MotoG3-TE using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sourabhtk37** [comment]
Can we finalise this talk for our next meetup(13th August, Sunday)?

**Comment by rajudev** [comment]
@sourabhtk37 finalise this talk

**Comment by sourabhtk37** [comment]
@lbsrex Thanks for the great workshop :100: 
Please share the slides and any accompanying code for this workshop so we could add it to the talks log. :)

**Comment by mysticTot** [comment]
@lbsrex will please provide slides of your talk?

**Comment by sourabhtk37** [comment]
Closing this as complete.
