### ISSUE TITLE
Intro to FOSS and sharing my experience with FOSS

### ISSUE THREAD

**Issue by Manas-kashyap** [ILUGD/talks#33]
It will be a short and beginners level intro to Foss and will share my experience with FOSS , and how i became more comfortable with it . 
My slides will be just a over view, i would like to interact with newbie's . 

Link to my slides
https://github.com/Manas-kashyap/INTRO-TO-FOSS-

**Comment by sourabhtk37** [comment]
Can we finalise this talk for our next meetup on 12th of August?

**Comment by Manas-kashyap** [comment]
Yes sure,

**Comment by bhanuvrat** [comment]
@Manas-kashyap 
instead of uploading pdf / odp files to github, try using http://lab.hakim.se/reveal-js/#/ 

you might like it.

**Comment by bhanuvrat** [comment]
also, avoid leaving your phone number on the sildes.
might not feel like a big deal today, but ...

**Comment by manasb** [comment]
@bhanuvrat 
https://github.com/ILUGD/talks/issues/33#issuecomment-321740988

That is nice but would not be available offline, PDF files can be saved for offline viewing and sharing.

**Comment by manasb** [comment]
@Manas-kashyap 

I looked through your slides, it seems like a really nice talk! 
It's great that there are people like yourself advocating for FOSS.

Thanks :D

**Comment by sourabhtk37** [comment]
Closing this as complete.
