### ISSUE TITLE
problems with ToR 

### ISSUE THREAD

**Issue by beyondszine** [ILUGD/talks#34]
**Abstract**
The talk will cover the main problems faced by ToR network.  Probably I will be taking on 3-4 problems and try to address the issues and shortcomings of those.  
        
**Expected Duration**
One hour

**Track**
        - Intermediate

**Pre-requisite**
        - Computer Networks  and protocols like TCP/UDP

Pre-requisites
        - Tor & ToR Faqs 

**Slides**
I am making those.  Let me know if we have time slot, will prepare accordingly.

**Comment by beyondszine** [comment]
@sourabhtk37 any update on this ?

**Comment by sourabhtk37** [comment]
Thanks for the proposal. Please share resources required for this talk. If slides are prepared please share them too. 
Questions:
- Is there a hands-on session?
    - If not, will you require 60 minutes or 30 minutes will do?
Please share the topics so we could properly allocate time for the talk.

**Comment by cocoa1231** [comment]
Excited for this one!

**Comment by beyondszine** [comment]
@sourabhtk37 I haven't prepared slides yet.  Will do by tomorrow.  Its no hands on session.  Its all hardcore networking and protocols understanding.  30 minutes might do if audience consists of sysadmins and networking professionals otherwise I will have to cover the basics of ToR also and that will take 1 hour.

**Comment by sourabhtk37** [comment]
Alright. Thanks for the update. Can we finalise this talk for our next meetup on 13th of August (Sunday)?

**Comment by beyondszine** [comment]
@sourabhtk37 yeah done! You all are most welcome at our workplace Innov8 CP.

**Comment by rajudev** [comment]
Cool, @sourabhtk37 lets get this in schedule.

**Comment by aurabindo** [comment]
@beyondszine Thanks for the great talk! ;)

**Comment by sourabhtk37** [comment]
Very engaging talk. I thoroughly enjoyed a lots of TIL. @beyondszine 
Please share any slides/resources accompanying for adding to talks log :)

**Comment by mysticTot** [comment]
@beyondszine Could you please add slides of your talk.

**Comment by manasb** [comment]
I would like to see the slides too. I just got to New Delhi late on Monday night or I would have attended the talk as well! :)

If there's interest, I can put something together for a future talk on I2P.

Looking forward to attending a meeting :D

Manas

**Comment by sourabhtk37** [comment]
>If there's interest, I can put something together for a future talk on I2P.
@manasb Sure, create an issue on this repository and people will review it.

Join https://www.meetup.com/ILUGDelhi/ if you haven't yet. :)

**Comment by rajudev** [comment]
@manasb If you are adding an issue on I2P, just a request from my side. Keep the full form of I2P in the title of your talk instead/along with the abbreviation. 'Invisible Internet Project' would draw more interest than 'I2P'

**Comment by beyondszine** [comment]
thanks all for the appreciation. 
I don't know if ppt could be of any use, majority of the interesting things are happen during conversations ;), still the link for the ppt, 
https://www.dropbox.com/s/8v1mfofbzjv2qt4/Problems%20with%20ToR.pptm?dl=0

**Comment by manasb** [comment]
[Problems with ToR.pdf](https://github.com/ILUGD/talks/files/1226821/Problems.with.ToR.pdf)

Hi, I had some difficulties viewing the .pptm file in LibreOffice. I've tried to generate a .pdf version for anyone else who may be using LibreOffice.

**Comment by rajudev** [comment]
@beyondszine Thanks for adding the presentation. Just a request to use pdf or an open document format so that people who are using LibreOffice, openOffice etc. should not have any problems viewing it. Thanks

**Comment by beyondszine** [comment]
@rajudev yeah that would be great, I forgot to do that.  i myself use libreOffice though, but I thought people like MS office more so made it in that again and uploaded that. Anyway, will take care of it for pdf version

**Comment by rajudev** [comment]
@beyondszine People do like MS Office including me. But you and I and us are ILUG-D . If not us who will pitch in for use of open document formats.

**Comment by mysticTot** [comment]
@rajudev I think we should mention this in guidelines.

**Comment by sourabhtk37** [comment]
Closing this as complete.
