### ISSUE TITLE
Building and utilizing a Network of Single Board Computer's (Raspberry Pi's and alikes)

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#35]
**Abstract**
This would be hands on guided workshop, one of a kind in which everyone present at the meetup will be involved. 
  We will divide the number of people present at the meetup in group's of 4-6 people each. This group will perform the following tasks in group. 

**1.** Each group will have a Raspberry Pi or any other SBC available to them. There task as a group is to setup there SBC with a running OS and required tools. 

**2.** Network this SBC to a central router by a wired/wireless interface. 

**3.** And perform any of the following tasks on there SBC. 
        **-**  Write and Host a local website on there SBC. It should be accessible locally by a URL in the form of an IP address by any PC/Phone within the network of the router. 
        **-**  Host a file storage/collaboration solution like NextCloud/OwnCloud etc on your SBC's. It should be accessible by any other device on the network. 
        **-** Setup a Media center server like Kodi. And host some Music and Videos there and serve it over the network so everyone else can enjoy it. 
        **-** More tasks will be updated in this list. 

      
**Expected Duration**
    2 Hours

**Track**
   	Beginner to Advanced, everyone will enjoy this. 

**Pre-requisite**
   	Not necessary, but good to have. 
Familiarity with shell, basics of networking, basic knowledge of servers (web and application servers)

        
**Resources**
    Raspberry Pi's with there own power adapters and a microSD card setup with the operating systems. 
(I'll bring one, hoping attendees will bring more)
Ethernet Cables to connect SBC which do not have wireless to be connected using wired interface. 
A router, I'll be bringing one along. 

**Slides**
    Content will be uploaded after the workshop.

**Comment by lbsrex** [comment]
Cool.

**Comment by rajudev** [comment]
धन्यवाद @sourabhtk37

**Comment by aurabindo** [comment]
@rajudev It was really good to have an interactive session!  Next time, I think we should have a page for the event. That way, we can indicate if we'd like the users to bring something, like Arduino or an SBC

**Comment by sourabhtk37** [comment]
We do have a meetup page for the meetup https://www.meetup.com/ILUGDelhi/

**Comment by sourabhtk37** [comment]
Awesome workshop @rajudev 
Please share any accompanying code/slides for today's workshop to be added to the talks log.

**Comment by rajudev** [comment]
The workshop was co-ordinated and became possible because of all of all of us. Since there was no slides and stuff. I'll add the resource links for the tasks that we asked people to do.

**Comment by rajudev** [comment]
one more request @sourabhtk37 If we can add a date to each issue about when the particular Talk/Workshop happened.

**Comment by sourabhtk37** [comment]
That will be added to the talks log, since this issue will be closed.

**Comment by sourabhtk37** [comment]
@rajudev Please update any resources for your talk in the talks-log section. Closing this.
