### ISSUE TITLE
Suggestion: Elementary OS

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [ILUGD/talks#37]
Elementary OS
How to host your own website on Raspberry Pi with dynamic IP.

**Comment by sourabhtk37** [comment]
@ShubhamTatvamasi Thanks for the proposal, but please add detailed description of the talk proposal so that people can review and suggest content more suited to them.

**Comment by rajudev** [comment]
@sourabhtk37 Can we get a new label for talk suggestions?

**Comment by rajudev** [comment]
got it added the label.

**Comment by sourabhtk37** [comment]
Closing this as no update.
