### ISSUE TITLE
I2P: The Invisible Internet Project - An Anonymous Overlay Network

### ISSUE THREAD

**Issue by manasb** [ILUGD/talks#39]
# Draft. Will be updated with more information

**Abstract**
The Invisible Internet Project (I2P) is a garlic routing using overlay network and darknet that allows applications to send messages to each other pseudonymously and securely. Uses include anonymous Web surfing, chatting, blogging and file transfers. The software that implements this layer is called an I2P router and a computer running I2P is called an I2P node.

The software is free and open source and is published under multiple licenses. The name I2P is derived from Invisible Internet Project, which, in pseudo-mathematical notation, is represented as I²P.

-- https://en.wikipedia.org/wiki/I2p
        
**Expected Duration**
45 Minutes + 15 Minutes for questions/discussion

**Track**
Beginner-Intermediate

**Pre-requisite**
Basic knowledge of networking, cryptography.
        
**Resources**
https://geti2p.net
https://en.wikipedia.org/wiki/I2p

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by sourabhtk37** [comment]
Thanks for the proposal @manasb 
It would be wonderful as we saw from interest in last meetup that questions/discussion to be added as part of the talk. This would engage the audience quite well and will ensure that whatever being talked about is useful to the audience. Sounds good?

**Comment by sourabhtk37** [comment]
Hey @manasb Would you be available on 26th August meet? If yes, can we finalise this talk for the meet on 26th of August?

**Comment by sourabhtk37** [comment]
Hey @manasb could you please update your availability and how to get in touch with you?

**Comment by sourabhtk37** [comment]
@manasb I don't see any response from your side, could you please update me regarding this talk?

**Comment by manasb** [comment]
Hi @sourabhtk37 sorry for the delay in responses. I have been trying to recover from jet lag and a subsequent cold. I am feeling better now!

I plan on spending time figuring out what should go into this talk over the next two weeks. 
I'll be chatting with I2P/i2pd/kovri devs and getting their input as well.

I will be out of the country from later this month until November, I think it's best to aim to give this talk in November.

---

I am available on Wire messenger (https://wire.com https://github.com/wireapp ) should there be any need to get in touch with me, my username is `@manas`

**Comment by sourabhtk37** [comment]
@manasb Status of talk? Available to give on 25th of Nov?

**Comment by Pradhvan** [comment]
@manasb update for 16 December?

**Comment by Manas-kashyap** [comment]
Are you ready to deliver this talk on 6 January meetup?

**Comment by Manas-kashyap** [comment]
Are you ready to deliver this talk on 6 January meetup?

**Comment by hellozee** [comment]
Available for 5th May?

**Comment by sourabhtk37** [comment]
Closing this as no response from proposer yet. 

@manasb feel free to open this again.
