### ISSUE TITLE
Playing with ptrace for fun and profit

### ISSUE THREAD

**Issue by adhokshajmishra** [ILUGD/talks#40]
**Abstract**
	The talk will focus on a single syscall (ptrace), and its usage in daily life of a developer and/or security fellow. Ptrace allows one to trace any process, stop it at desired points, read memory, write into process memory, inject code etc (basically, complete control). The talk will start from bare basics, and will proceed to how to control a process from a self coded teeny-tiny debugger. Creative uses in offensive security will also be explained (basically, how this can be used for malicious purposes).
        
**Expected Duration**
  60 minutes

**Track**
 Beginner / Intermediate

**Pre-requisite**
Attendees must be comfortable with Linux and cli shell (bash, zsh, fish, whatever); and must have some prior experience in C and/or C++.
        
**Resources**
   http://man7.org/linux/man-pages/man2/ptrace.2.html

**Slides**
   Will be updated in future

**Comment by sourabhtk37** [comment]
Thanks for the proposal @adhokshajmishra 
I was working on something similar to this, would be very interesting.
- Will we see some hands-on work for this talk?

**Comment by adhokshajmishra** [comment]
Yes. It will be part theory, part hands-on. Even better if attendees can follow it in parallel on their boxes.

**Comment by sourabhtk37** [comment]
Namaskar mishraji, Will you be available on 26th August and be able to give this talk? Let me know

**Comment by adhokshajmishra** [comment]
Unfortunately, no. How about next meetup?

**Comment by sourabhtk37** [comment]
Alright. Next meetup? Done.
Hope to see you soon.

**Comment by sourabhtk37** [comment]
It's time for the next meetup :tada: 
Can I see this talk in the next meetup (coming saturday that is) ? @adhokshajmishra

**Comment by adhokshajmishra** [comment]
This issue should be closed as I won't be able to deliver the proposed speech/workshop physically anymore (I have relocated to Mumbai). I am sorry for this.

**Comment by sourabhtk37** [comment]
Sorry to hear you go, we wish you success in your future endeavours. :heart:
Hope you get to connect with the large community in Mumbai.
