### ISSUE TITLE
understanding makefiles

### ISSUE THREAD

**Issue by ntavish** [ILUGD/talks#41]
**Abstract**
What makefiles are, and how to write them to do things.
        
**Expected Duration**
30 minutes

**Track**
    	- Beginner
     
**Resources**
make manpage etc.

**Comment by sourabhtk37** [comment]
Thanks for the proposal @ntavish 
Will there be hands-on session for creating a makefile for a codebase?

**Comment by sourabhtk37** [comment]
@ntavish Can we finalise this talk for the next meetup?

**Comment by rajudev** [comment]
not sure if it is relevant. @ntavish The most simple explanation of Makefile is what I have found here
https://git.fosscommunity.in/praveen/hello
May or may not come of use to you. Just posting it here

**Comment by sourabhtk37** [comment]
Lining up your talk for 16th Dec then @ntavish

**Comment by ntavish** [comment]
ok, done

**Comment by sourabhtk37** [comment]
Great.

**Comment by sourabhtk37** [comment]
Closing this.
