### ISSUE TITLE
How decentralized communications and Infrastructure work?

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#42]
**Abstract**
	Decentralization has always been the way in which services that used to be offered to people, be it e-mail, or p2p file sharing with torrents. But with time services got concentrated in the hands of the few like Google/Facebook/Microsoft to name a few. Services from being de-centralized earlier, got concentrated in the hands of a few corporations. To such a level. that sometimes that there are no alternate options available. This talk would Introduce people to the concept of federation and decentralization in today's world. It would also list down various very good alternatives to the centralized services that we use today. 

**Expected Duration**
30 minutes to 45 minutes

**Track**

Beginner

**Pre-requisite**
none, but knowing about basics of servers/networking would be beneficial. 
        
**Resources**
[1] https://prism-break.org/en/
more will be added soon. 

**Slides**
    Will be added after the meetup.

**Comment by sourabhtk37** [comment]
Finalise for next meetup? @rajudev

**Comment by rajudev** [comment]
@sourabhtk37 nope. We are having SFD. I don't think I'll be able to takeout time for this at the SFD meet.

**Comment by rajudev** [comment]
@sourabhtk37 may be we should skip this one for next meetup as well. Lets make our next meetup more of an hands-on fest.

**Comment by mryashbhardwaj** [comment]
can we please have this in the coming meetup

**Comment by sourabhtk37** [comment]
If he is available then sure @mryashbhardwaj :)

**Comment by mryashbhardwaj** [comment]
@sourabhtk37    lets have it when he comes back

**Comment by rajudev** [comment]
I would be coming up to the next meetup, but I would prefer this to be postponed. If we would have no other talks lined up, In that case I'll consider taking up this one.

**Comment by sourabhtk37** [comment]
@rajudev Meetup on 6th at Fueled. Are you available to give this talk?

**Comment by rajudev** [comment]
I would be attending, but can't prepare for the talk yet due to work commitments. Only in case of us not getting a speaker, I'll be giving the talk.

**Comment by hellozee** [comment]
Confirmed for 14/15th April

**Comment by philo-math** [comment]
@rajudev Can you add all the decentralized alternatives to facebook, twitter etc. at one place for us to refer?
