### ISSUE TITLE
A competition on Designing through open source softwares like krita , inkspace .

### ISSUE THREAD

**Issue by Manas-kashyap** [ILUGD/talks#43]
It will be a competition of Designing a poster or any pic to something great.
        
**Expected Duration**
30-45 min

**Track**
As it's a competition so, we don't know the level they will compete at.

**Pre-requisite**
   	Laptop with pre-installed any open-source designing platform like Krita, inkspace or any else.

**Comment by rajudev** [comment]
Please include more detailed description on the issue. 
What exactly do you want to do?
What exactly is the competition and stuff.

**Comment by Manas-kashyap** [comment]
It will be a competition for those who already know and for beginner , it will be a group task and we will help them out to do it .
exactly thier task will be , to make a poster for any event , we will name it and let the creativitiy flow

**Comment by sourabhtk37** [comment]
Please add details to the top-post itself. Put in a very clear, descriptive manner and not in vague terms.

**Comment by sourabhtk37** [comment]
Closing this as no update is provided.
@Manas-kashyap You can update either by creating a new issue or requesting to reopen it when you're ready.
