### ISSUE TITLE
Linux Install Fest

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [ILUGD/talks#44]
**Abstract**

When linux was new and many people didn't knew how to use linux or even install linux on their machines, at that time LLUG (Linux Local User Group) used to do **Install Fest** every month. At the Install Fest they invite all the people who are new to linux and didn't knew how to install linux or have installed linux but were facing some issues with installing proper drivers or software. At this meet we will come forward to face all these issues that people are facing in their day to day use.

**About**

- We will Install linux on people laptops.
- We will solve people facing the driver issues.
- For those who are dependent on windows applications we will find free linux FOSS (Softwares) for them.
- Will teach everyone tricks how you can save time using linux with your day to day work.

**Pre-requisites**

- Love for Linux
- Will to Learn

**Expected duration**

Full day, It will be called **Linux Install Fest**

**Level**

Beginner

**Resources**

I got my Inspiration for doing this from a very popular movie called **Revolution OS**.
I have linked the scene below where they are having the Install Fest Day.

[Revolution OS - Install Fest](https://youtu.be/GsHh2wfy_-4?t=56m40s)

**Speaker Bio**

I will be needing everyone using linux to help make this event possible.
This will not be a speakers day, It will be a day for everyone by everyone.
Everyone is welcome to help and show the true powers of linux.

**Comment by sourabhtk37** [comment]
Closing this as complete.
