### ISSUE TITLE
Introduction to Git 

### ISSUE THREAD

**Issue by vipulgupta2048** [ILUGD/talks#45]
**Abstract**
This talk would be about Version Control System, Git, GitHub and Git workflow. Git is used for projects to make them more stable, organized and secure increasing both efficiency and productivity. This talk would be completely hands-on. Theoretical topics will be not discussed, therefore it is advised to check resources. The attendees would get to learn the basics of how to fork and clone a repository, adding their changes to the staging area, committing those changes and then pushing the changes. By actually doing it on their systems. Which would be both interactive and help them learn better and faster.      

Attending this workshop will enable the attendees to work and explore more of Git and Github Including branches, merging, rebase and updating. If successful, we can have an Intermediate session on it too. It would also help people understand how communities operate on this platform and how they can contribute.   

**Expected Duration**
30-45 minutes

**Track**
Beginner   

**Pre-requisites**
System with Git (Bash) Shell installed and configured. A GitHub account should also be made.
For MacOS - http://git-scm.com/download/mac
For Windows - http://msysgit.github.io/
For Linux - http://git-scm.com/book/en/Getting-Started-Installing-Git

**Resources**
Have some familiarity with Version Control System (VCS), git and Github as we are just gonna brush-up on these topics. Google them up, read their history, use, and importance. Whatever you find.

**Slides**
https://docs.google.com/presentation/d/1dLshLydrBL8t_X3nvOodi-LkH8iORocy8uadGrlslGc/edit?usp=sharing

**Comment by sourabhtk37** [comment]
Please share slides for the workshop @vipulgupta2048

**Comment by vipulgupta2048** [comment]
I have shared the link for my slides. Would that be sufficient ?
