### ISSUE TITLE
How the Linux Desktop is Built

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#46]
**Abstract**
Windows and Mac have an opaque and monolithic User Interface, whereas Linux is more modular. This often leads to a shit ton of confusion for new Linux users on exactly what a DE, DM, X.org, or anything is. This can be cleared up pretty quickly (I think) if we show people how to build their own Desktop Envs from scratch. Stuff that should be covered in chronological order:

* Xorg
* Window Managers - twm for a intro, then maybe openbox, and just to show that there is another way to manage windows, i3wm or some other tiling window manager
* Login/Display Managers - Uptill now, we used startx to start the X11 desktop server. Now we can use graphical interfaces to do this for us!
* GTK toolkit/Qt toolkit
* Finally putting it all together, the Linux Desktop Environment!
        
**Expected Duration**
45 to 60 minutes

**Track**
Beginner
**Pre-requisite**
Basics of the Linux Shell
        
**Resources**
Will add resources later

**Slides**
Not sure if there'll be any slides
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by satyaakam** [comment]
Be clear what you want to talk about Linux the kernel or the GNU/Linux as an operating system.The Linux kernel is Monolithic compare it with the Microkernel architectures. So overall it  depends what you want to talk about and what your understanding of what you mean an Operating system is and what you want to convey. Looks like you want to show the ease of use of changing the environments and plug and play nature of the whole ecosystem.

**Comment by cocoa1231** [comment]
I think I made it clear that I want to show how the Linux GUI is structured. Starting with a base arch Linux install, showing the audience how a desktop step by step comes into structure would give people a better idea of how a Linux Desktop environment is made

**Comment by sourabhtk37** [comment]
Great talk. Looking forward to see more talks. @cocoa1231 
Any slides/scripts to add to the logs?

**Comment by cocoa1231** [comment]
[Uploading How_the_Linux_Desktop_is_built_(Script).pdf…](I just had this script)

**Comment by cocoa1231** [comment]
[How_the_Linux_Desktop_is_built_(Script).pdf](https://github.com/ILUGD/talks/files/1505926/How_the_Linux_Desktop_is_built_.Script.pdf)
