### ISSUE TITLE
Schedule for Meetup at Bhagwan Parshuram Institute of Technology, Delhi

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#47]
#Meetup Date: Sunday 8th October 2017

Expected availablity of Venue:
9am - 5pm

Time of meetup:
10 am to 5pm

Food:
Sourabh: will discuss with college for sponsoring/reimbursement

 
 10:00 - 10:25     Introduction to Open source and Linux #55 
 
 10:30 - 11:30     Installation Demo (How to install linux) #48 

 11:30 - 11:40     Networking break
 
 11:40 - 12:40     Applications and GUI Overview
                         - What is DE, login managers, Window manager? #49  (**This talk/workshop is already assigned**)
                         
 12:40 - 01:30     Lunch/Snacks
 
 01: 30 - 02:00    Performing common tasks on linux #52 (**This talk/workshop is already assigned**)
                          - Q/A on linux
 
 02:00 - 02:30     Software development on linux #53 (**This talk/workshop is already assigned**)

 02:30 - 3:00      Basics of Shell #51 (**This talk/workshop is already assigned**)
 
 3:15 - 3:30        Networking Break 
 
 3:30 - 4:15        Software Development using Version Control System (git) #45 (**This talk/workshop is already assigned**) 
 
 4:15 - 5:00       Linux Install festival  #44

**Comment by rajudev** [comment]
Discuss any changes/additions/removals from schedule on this issue.
Discuss about the content of Individual issue on the respective issue number.

**Comment by ShubhamTatvamasi** [comment]
I think we should call it "Linux Install Fest" instead of "Linux Install Festival". Because when this whole thing started in US they used to call it "Linux Install Fest". I think it looks more classy :)

**Comment by rajudev** [comment]
Okay, I think that. Let's rename it to that then

**Comment by rajudev** [comment]
And I guess wrong issue is added here in the list

**Comment by rajudev** [comment]
Corrected the issue number for that

**Comment by sourabhtk37** [comment]
Just for the discussions sake, we don't do stuff just because people used to do that way back in the day. 
I am of opinion that one should make the world adapts to you, no believed electric cars would be possible in production and here we are because the world doesn't know what it needs. Way back I was extremely satisfied with Nimbuzz(those days :heart: ) and SMS but now I want all those messaging services.

**Comment by rajudev** [comment]
Change is good. But it should not always be necessary. Unless it is improvising on the previous situations. 

BTW, those days :)
I used to use Nimbuzz on J2ME phone. 
Do you remember mig33?

**Comment by rajudev** [comment]
People used to export SMS messages to files and store them. Because they wanted to cherish the messages in them. 
Now have changed so much. And so much content is available now that no one wants to save anything on phone.

**Comment by sourabhtk37** [comment]
>Do you remember mig33?
God, you are old @rajudev 

Anyways, I think we can remove Installation demo since we will be doing that anyways in `Linux Install fest` section and each distro have it's own installation steps.

**Comment by rajudev** [comment]
>अभी तो मे छोटा सा नन्हा सा बच्चा हुँ

I still think, we should keep Installation demo as it will give them the chance to think about hard disks/BIOS/File Systems/ Boot Order/Grub/ etc. otherwise we will have to explain it all to them during install fest.

**Comment by adityajai007sonu** [comment]
Basic Session , Add something cool like Crytocurrency , Big Data etc etc

**Comment by sourabhtk37** [comment]
*Need changes in timing*
The first networking break is quite small `11:30 - 11:40` it can be increased to 20mins by reducing the time for lunch which is at `12:40 - 01:30` i,e 50mins, it can reduced to 30mins. 

- Installation demo
    It is alloted 1hour but can be done in 30mins or less.
- Applications and GUI Overview
    This one is allotted 1hour but can be covered in less than that.

And is it okay to start Install fest in parallel to the git workshop?

**Comment by sourabhtk37** [comment]
@adityajai007sonu I don't understand what exactly you are proposing. Could you add a bit more details to your suggestion. Is this for the current meetup we are having or in general. If in general, please create a suggestion by creating an issue on the issues tab and people will take it up.

**Comment by sourabhtk37** [comment]
Thanks everyone for your effort. Closing this now.
