### ISSUE TITLE
Installation Demo (How to install linux)

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#48]
**Abstract**
An installation of a Linux distro (probably mint or a flavor of Ubuntu) will be performed live and each step explained to set the stage for the install fest
        
**Expected Duration**
1 Hour

**Track**
Beginner

**Pre-requisite**
None. mostly. 
        
**Resources**
Download [Ubuntu](https://www.ubuntu.com/download/desktop) or [Linux Mint](https://linuxmint.com/download.php):

**Slides**
Pretty sure no slides here
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by rajudev** [comment]
Time reduced to 45 minutes. Speaker will be cocoa. Other's can pitch in when required.

**Comment by sourabhtk37** [comment]
Alright. Fair enough.

**Comment by sourabhtk37** [comment]
Closing this as complete.
