### ISSUE TITLE
Applications and GUI Overview

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#49]
**Abstract**
This talk/session will briefly cover how the Linux GUI is structured. It will touch upon the concept of a Login Manager, a Desktop Environment and a Window Manager  
        
**Expected Duration**
1 Hour

**Track**
Beginner

**Pre-requisite**
None
        
**Resources**
[This](https://www.youtube.com/watch?v=866-MpRATnM&list=PLTXMX1FE5Hj7JmR73CQDXkNq8OVn9_Z6F) Youtube series goes in depth into the Linux desktop, so for people who wanna dig in, dig in!

**Slides**
None
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by rajudev** [comment]
The list of GUIs that we are going to cover. Add the ones you want here..
Adding the usuals.
Gnome
KDE
Cinnamon

Compiz enabled lxde

**Comment by sourabhtk37** [comment]
@cocoa1231 Are you sure you will built login managers, wm and a de live?

**Comment by cocoa1231** [comment]
@sourabhtk37 As long as I get a pen drive, a working internet connection, and 1 hour alone with the computer, then yes. But we won't do that in this talk, I made a separate issue for the talk that goes in that deep. This will be a surface level talk. We'll do the more in depth talk on the next to next LinuxChix or ILUG-D

**Comment by rajudev** [comment]
This session would be taken by your's truly @rajudev

**Comment by sourabhtk37** [comment]
Closing this as complete.
