### ISSUE TITLE
Linux Install festival

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#50]
**Abstract**
A place where you can get a Linux desktop installed on your own computer. 

**Expected Duration**
  1 hour or more. 

**Track**
   	        

**Pre-requisite**
   	none

**Comment by rajudev** [comment]
sorry @sourabhtk37 just looked issue #44

**Comment by rajudev** [comment]
@sourabhtk37 as a standard practice every where, whenever you add a duplicate label, also tell of which issue it is duplicate of.

**Comment by sourabhtk37** [comment]
Yup will do. :+1:
