### ISSUE TITLE
Basics to Shell

### ISSUE THREAD

**Issue by hellozee** [ILUGD/talks#51]
**Abstract**
       Linux basics to get new users on their feet, covers getting started with the terminal, the Linux 
       command line, and executing commands. If someone is new to Linux, he/she will want to familiarise 
       himself/herself with the terminal, as it is the standard way to interact with a Linux system. Using the 
       command line may seem like a daunting task but it is actually very easy if someone starts with the 
       basics, and build skills from there.
        
**Expected Duration**
       30 minutes

**Track**
       Beginner

**Pre-requisite**
   	Running Linux System

**Slides**
https://hellozee.github.io/#/

**Comment by sourabhtk37** [comment]
@amzee Would you like to take this up?

**Comment by amzee** [comment]
@sourabhtk37 , I don't think I am well enough for that, I can surely assist though.

**Comment by sourabhtk37** [comment]
Are you implying that you are not well, as in health-wise or experience wise. If latter then I should recommend you try taking this on as a learning experience for public speaking. I am sure it will help a lot and able to express your thought clearly and carefully. Meanwhile you will be able to dig dipper into core concepts and understand them clearly. Let me know.

**Comment by amzee** [comment]
Experience wise, anyway I was also thinking of giving a talk but on a different topic on which I have done proper research and have a little experience too, like alternatives to creative suit. Up to now all I have done is copying and pasting from google, :sweat_smile:

**Comment by rajudev** [comment]
I am excited to see @hellozee giving a talk.

**Comment by sourabhtk37** [comment]
Please share the slides for this talk @hellozee

**Comment by hellozee** [comment]
@sourabhtk37  I have already attached the link in the description

**Comment by sourabhtk37** [comment]
Closing this then.
