### ISSUE TITLE
Performing common tasks on linux

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#52]
**Abstract**
This session will cover how someone would perform the day-to-day tasks like browsing the internet, creating a document, connecting to wifi, etc. on a Linux system, as well as a public Q/A for anything that's not covered. Or just anything. Ask away!
        
**Expected Duration**
30 Minutes

**Track**
Beginner

**Pre-requisite**
I think the only thing you need to know is covered in the previous talks
        
**Resources**
https://itsfoss.com/adobe-alternatives-linux/

    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by sourabhtk37** [comment]
I will be taking up this talk and moderating the Q&A.

**Comment by sourabhtk37** [comment]
Closing this as complete.
