### ISSUE TITLE
Software development on linux 

### ISSUE THREAD

**Issue by hellozee** [ILUGD/talks#53]
**Abstract**
	An introduction to how a piece of software can be developed in linux. It primarily revolves around 
        installing various IDEs (code::blocks,eclipse,netbeans) and compilers (gcc) to use them for proper 
        development.
        
**Expected Duration**
        30 mins

**Track**
    	Beginner

**Pre-requisite**
   	Working Linux System

**Comment by sourabhtk37** [comment]
@bhanuvrat is the allotted time enough?

**Comment by sourabhtk37** [comment]
@vipulgupta2048 please share the docs file saved on your computer for this talk

**Comment by vipulgupta2048** [comment]
#60 PR submitted. The .txt file I saved is in there.
