### ISSUE TITLE
Software development on linux

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#54]
**Abstract**
This one is going to show you how to install software development tools on Linux, such as IDEs (Eclipse, Android Studio, Geany, etc.) and show you how easier and more powerful it is to do it FOSS style
        
**Expected Duration**
30 Minutes

**Track**
Beginner

**Pre-requisite**
A working Linux system, which you will get after the install fest!

---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by cocoa1231** [comment]
Whoops. Sorry

**Comment by yashwithgm** [comment]
Libreoffice suck
