### ISSUE TITLE
  Introduction to Open Source and Linux

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#55]
**Abstract**
	A brief introduction to what open source software/hardware is all about. Followed by an Introduction to Linux as an operating system
        
**Expected Duration**
30 minutes

**Track**
   	- Beginner
        
**Pre-requisite**
  none
      
**Resources**
will be decided in comments by everyone. 
**Slides**
    Links to the slides.
if there are any, will be added later after the meetup.

**Comment by rajudev** [comment]
We can talk collectively on this with bits from many LinuxChix or ILUG-D members

**Comment by sourabhtk37** [comment]
More like a discussion?

**Comment by rajudev** [comment]
@sourabhtk37 Yes, but mediated by one guy/girl. So we stay on track.

**Comment by rajudev** [comment]
It will be a collaborative talk between many people from both LinuxChix and ILUG-D together mediated by one person(probably me :)

**Comment by sourabhtk37** [comment]
Perfect.

**Comment by sourabhtk37** [comment]
Closing this as complete.
