### ISSUE TITLE
Schematic Capture & PCB Layout in KiCad

### ISSUE THREAD

**Issue by aurabindo** [ILUGD/talks#56]
**Abstract**
The workshop will cover the CAD tool KiCad to generate design files for Printed Circuit Boards. Basic knowledge of electronics will be added advantage for the attendees. Workshop will cover:
* Schematic Capture of a circuit in Eeschema
* PCB Layout & Gerber Generation in Pcbnew
        
**Expected Duration**
    1.5 - 2 hours.

**Track**
        - Intermediate

**Pre-requisite**
   	Optional: Installation of KiCad on their laptops (nightly version preferred)
        
**Resources**
    http://kicad-pcb.org/

**Slides**
    https://aurabindo.github.io/KiCad_talk

**Comment by rajudev** [comment]
Thanks for the proposal Aura. Would be interesting to attend this one.

**Comment by sourabhtk37** [comment]
Images seems to be overflowing from the slides, is that expected behaviour?

**Comment by aurabindo** [comment]
Since the images are not any functional/block diagrams, it is not very relevant. Although I do need to fine tune the slides a bit. This is more of a demo cum talk. Second year engineering students from CS, EE, EC etc who do not have any experience using a PCB design software would find it useful.

**Comment by rajudev** [comment]
@aurabindo You should also consider people like me, who are interested in electronics, but are not from the Electronics branch. And many people like me would be there. Make sure that the talk would not be Jargon fest for us. 
Aside from that, how do you find fritzing compared to kicad?

**Comment by aurabindo** [comment]
@rajudev I am not very confidant that in 2 hours all those [scary 😆 ] things can be covered.

Fritzing works good in the context of arduino. But I have not used it per se. If most of the crowd would prefer Fritizing instead, I will give it a shot and do a demo on that instead.

**Comment by rajudev** [comment]
@aurabindo I don't mean you to shift the talk towards fritzing. 
I just asked if you have used that. Since that it is the only PCB design software that I had my hands on for some time. 
I got my answer.

**Comment by sourabhtk37** [comment]
@rajudev @lbsrex Pls to finalise this as I am no expert in this field.

**Comment by sourabhtk37** [comment]
@aurabindo What's your availability on 25th Nov?

**Comment by aurabindo** [comment]
@sourabhtk37 please move it some time after Jan 1st week

**Comment by sourabhtk37** [comment]
Not available on 6th. Moving this talk to February meetup.

**Comment by hellozee** [comment]
@aurabindo will you be available on 14th or 15th April

**Comment by philo-math** [comment]
@aurabindo will you be available for our next meetup on 30th June 2018 or 1st July 2018?

**Comment by hellozee** [comment]
@aurabindo will you be available on 11th August for delivering this talk?

**Comment by hellozee** [comment]
@aurabindo will you be available on 8th September?

**Comment by aurabindo** [comment]
@hellozee  I'm really sorry, I was out of GitHub for a while. Besides, I moved out of Delhi! So this talk wont be possible! Apologies again! I'm closing this.

**Comment by hellozee** [comment]
@aurabindo ohh no problem
