### ISSUE TITLE
Alternatives to Adobe Creative Suite

### ISSUE THREAD

**Issue by hellozee** [ILUGD/talks#58]
**Abstract**
Adobe Creative Suite is, by far, the industry champion when it comes to graphic design software. Even with its occasional technical issues present with virtually every version update, it remains to be the best package in the market. It's practically used by everyone who wants to (and actually dabbles in) graphic design. But the problem is they don't provide any Linux builds, so I will be talking about various alternatives to it and weigh out their pros and cons.
        
**Expected Duration**
    30 mins

**Track**
    	- Beginner

**Pre-requisite**
   	None

**Comment by mysticTot** [comment]
@hellozee  please add slides

**Comment by hellozee** [comment]
@mysticTot  I am thinking of giving it without slides, by showing the demos of the application I am talking about.

**Comment by sourabhtk37** [comment]
I don't see a value in this talk. Merely listing the pros and cons of some software over another is not something I would personally attend but rather a run down through one of the software and get to see how things are done in that software.
[This](http://www.techradar.com/news/software/applications/10-free-open-source-alternatives-to-adobe-creative-suite-1305714) will summarise your talk.

**Comment by hellozee** [comment]
@sourabhtk37 actually I am also feeling the same, it wont be able to cater the need of the particular audience you people are trying to reach, almost all of the persons present in audience only know/use Photoshop that also for minor tasks and wont ever use a whole creative suite leave alone other software for creative stuff. And my talk will revolve around those 'other' things rather than Photoshop. Also please I am begging don't put any random article from google as a summary of my talk.

**Comment by sourabhtk37** [comment]
> don't put any random article from google as a summary of my talk
Exactly my point.

**Comment by mysticTot** [comment]
@hellozee You can deliver 5 minutes lightning talk.

**Comment by hellozee** [comment]
@mysticTot nope I am writing a blog on it, @sourabhtk37 you messed up with the wrong person..

**Comment by sourabhtk37** [comment]
No trolling here please @hellozee 
We would love to have a talk by you at our next ILUG-D meetup. Apologies for people taking over your talk last meetup but you should be able to take up one on your own for next meetup.
Good luck :heart:

**Comment by hellozee** [comment]
@sourabhtk37  why are you dragging the talk from previous meetup?  Apologies for what? I can't understand the audience properly that's my fault. 
> This will summarise your talk
This is going to hurt you

**Comment by mysticTot** [comment]
@hellozee Please accept the decision made over your talk.
Folks here review talks for a reason. It is an organisation. Please read guidelines about how to communicate.
Further, this repo is visible to everyone.

**Comment by hellozee** [comment]
@mysticTot I think you people are misunderstanding me, I have closed the talk for a reason, 

> It wont be able to cater the need of the particular audience you people are trying to reach, almost all of the persons present in audience only know/use Photoshop that also for minor tasks and wont ever use a whole creative suite leave alone other software for creative stuff. And my talk will revolve around those 'other' things rather than Photoshop.

I am on @sourabhtk37 for another reason.

**Comment by mysticTot** [comment]
@hellozee You can contact/talk to @sourabhtk37  in person for any personal issue.
 Please don't put off topic things/comments here.

**Comment by hellozee** [comment]
@mysticTot yup done that, sorry for dragging that here ✌️✋🙈😔

**Comment by mysticTot** [comment]
No worries. But for the next  time remember these things. :-)
