### ISSUE TITLE
Coding and configuring a webApp with a remote database server under 3 hours. 

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#59]
**Abstract**
	
Attendees of our previous meetup at innov8 enjoyed the small hackathon that we did with Raspberry Pi's. This time I present to you another hackathon but with different challenges this time. Making sure that everyone gets to learn and improvise there skills this time. 

Like before, I am conceptualizing the hackathon format. But it will require participation of knowledgeable ILUG-D volunteers to conduct this together. This will be a team effort. 

The following tasks would be done in a team of 4 persons per team. The teams would be formed in a proper way this time. Also making sure that each team has a person to guide the group along the way.

This would be a hands-on hackathon. We would be doing the following within a short time frame. 
- Build a website which sends and recieves data from a remote database server.
- Install and configure a remote database server.
- setup sync and replication of database between the multiple remote database servers. 
- real time sync on the client side with the remote database. And we will try to a real-time sync of databases between all the computer nodes that we will have at the meetup. 
- And at the end we will have fun trying to hack and crash each others database servers and breaking the built setup. 
       

**Expected Duration**
    120 to 180 minutes. 

**Track**
Beginner
  - Simple enough to be understood by a beginner. Complex enough to be configured by a professional. 
- This is a must attend for students as well as professionals. This hands on hackathon will give you a brief overview of a website/application/webApp on both the client and server side. 

**Pre-requisite**
 -  HTML Basics. Additional knowledge of a bit of CSS/JavaScript will help as well.
 - Make sure you bring your laptops with you
        
**Resources**
    
Mozilla Developer Network website for HTML/CSS/JS basics
Remote database server = couchDB
Client side local storage of data = pouchDB

**Slides**
    If any will be added after the meetup.

**Comment by tucosaurus** [comment]
Where do you intend to get the required number of remote servers for this ?

**Comment by rajudev** [comment]
@tucosaurus That is exactly where the fun begins. How do we get the remote servers? 
No we don't use remote servers as in the out of physical area of the venue. (If someone has an EC2 instance/VPS of there own, they can use it if they want.)

 Instead we create machines locally on our systems or on a particular system in a team. 
That remote system, can be a VM/LXC/Docker container.We can install the required server side software in that machine. 
It is upto a particular team on how they wan to install the server side software. It can also be running on the same machine server over a particular port. It is upto a team how to approach the problem. We would be distributing hints for the teams who won't be able to figure out things. 
We can install the required server side software in that machine. 
I have got the whole plan. And I am certain that it can be finished under 3 hours.

**Comment by tucosaurus** [comment]
Okay. Please share your plan here. Also, list the things that we as organizers would need to conduct the event smoothly , like I think that we would need to set up a docker registry at the event for the images that the participants will be using since the internet might be flaky.

**Comment by rajudev** [comment]
@tucosaurus Yeah, we can setup an offline docker registry, another easy option is an LXC container. 
I have a local Debian Repository on my system already. People can pull packages for Debian/Ubuntu or many other distributions directly from the URL of my system at the venue. 
So I will list a more detailed plan here soon then.

**Comment by hellozee** [comment]
@rajudev a VM will be far more easier to setup than an lxc/docker container, wont be?

**Comment by rajudev** [comment]
@tucosaurus @hellozee I would put a problem statement in front of you. It would be upto you guys, on how you want to approach towards it. VM/Docker/LXC/Chroot are all just the different ways in you can do that. 

on the side note: VM is easier to setup, but requires static allocation of resources of the host machine to the VM. While Docker/LXC do run as a process on the host and scale up/down as needed.

**Comment by amansinu** [comment]
How can I register and what is registration charge

**Comment by sourabhtk37** [comment]
@amansinu You can RSVP on the meetup page [here](https://www.meetup.com/ilugdelhi/events/242531827/) and there's no registration charges, it's free of cost.

**Comment by bharatvarshney8989** [comment]
Is there any upcoming meetup for Devops like docker, container..

**Comment by sourabhtk37** [comment]
We had one yesterday on docker but you can suggest talks by creating proposals as github issues.

**Comment by bharatvarshney8989** [comment]
Could you please again share us the all information

**Comment by sourabhtk37** [comment]
What information do you want? Can you be a bit more specific? @bharatvarshney8989

**Comment by bharatvarshney8989** [comment]
Hello Sir,

Please share basic about Docker , i m new in docker so in future i can
prepare myself



*Thanks & Regards*
Bharat Varshney
Software Test Engineer | www.rosmertatech.com
*Certified ISTQB Professional*

 "I believe, *The More You Learn The More You Play…!"*

**Comment by sourabhtk37** [comment]
@bharatvarshney8989 Pls join us on [telegram](https://t.me/joinchat/AAAAAEAc48wCHkUXViXBcg).

**Comment by bharatvarshney8989** [comment]
ok sir

*Thanks & Regards*
Bharat Varshney
Software Test Engineer | www.rosmertatech.com
*Certified ISTQB Professional*
ItsMyURLs.com/bharat567var7


 "I believe, *The More You Learn The More You Play…!"*
