### ISSUE TITLE
CryptoCurrency CPU Mining on Linux (Debian/Ubuntu)

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [ILUGD/talks#61]
**Abstract**

I will be guiding how you can do CryptoCurrency CPU Mining on your Debian based Linux distro, it will be a hands on demo a step by step guide for Mining CryptoCurrency.

**About**

- Creating the CryptoCurrency wallet
- Understanding the Coin's Algorithm
- Selecting the pool
- Calculating the hash rates

**Pre-requisites**

- Debian based Distro

- Basics of linux command line

**Expected duration**

30 Minutes

**Level**

Beginner

**Resources**

[Got Time? Read This!](https://medium.com/@shubhamtatvamasi/how-to-mine-elements-coin-with-cpu-on-windows-and-linux-debian-ubuntu-6ddc6d764202)

**Speaker Bio**

I am working on CryptoCurrency Mining systems for last 6 months. I give solutions to large Enterprises on setting up there Mining farms.

**Comment by ShubhamTatvamasi** [comment]
Just not on the 28th October, because I will be at PyDelhi on that day.

**Comment by mfrw** [comment]
@ShubhamTatvamasi Thank you for creating the issue

**Comment by tucosaurus** [comment]
@ShubhamTatvamasi Can we put in your talk for our meetup on 16th December (which is tomorrow) ?

**Comment by ShubhamTatvamasi** [comment]
Not possible for tomorrow, quite busy in Blockchain Conference.
