### ISSUE TITLE
Should I go ?

### ISSUE THREAD

**Issue by mfrw** [ILUGD/talks#64]
**Abstract**
We introduce golang, and answer the question of why should we learn a new language if at all.
        
**Expected Duration**
  60-70 mins

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner

**Pre-requisite**
   	Just you and some of your attention.
        
**Resources**
blog.golang.org

**Slides**
    Not yet ready
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by sourabhtk37** [comment]
I was not present there for your talk but I believe it would have been great. Looking forward to many more talks from you @mfrw 
Any slides accompanying your talk?

**Comment by mfrw** [comment]
Sure, GitHub.com/mfrw/letsgo

**Comment by sourabhtk37** [comment]
Thanks. Closing this.
