### ISSUE TITLE
How programs get run in Linux

### ISSUE THREAD

**Issue by sourabhtk37** [ILUGD/talks#66]
**Abstract**
	TBD
        
**Expected Duration**
    1hr
**Track**
        - Intermediate 
        
**Resources**
    https://lwn.net/Articles/631631/

**Slides**
    TBD

**Comment by Manas-kashyap** [comment]
This could be a good talk, we can finalize it.

**Comment by sourabhtk37** [comment]
There is no content as of now, I will develop this soon and update. Check other talks in line.
