### ISSUE TITLE
Compiling Android Kernel for your own device

### ISSUE THREAD

**Issue by LordArcadius** [ILUGD/talks#67]
**Abstract**
	I will be telling about Android Kernel which is based on Linux kernel. We will obviously start from basics that what it is? how it works? And other stuffs like that. I will also explain how you can compile a custom kernel for your own device easily.

**Contents:-**
• About Android Kernel
• Why we need custom kernels
• How to compile a custom kernel
• Upstreaming kernel version and it's importance

**Expected Duration**
    45 minutes to 1 hour

**Track**
        - Intermediate

**Pre-requisite**
         • Any Linux destro
         • Basic linux commands
         • Little knowledge of Github
        
**Resources**
    [XDA Thread to learn compiling Android Kernel!](https://forum.xda-developers.com/android/software-hacking/reference-how-to-compile-android-kernel-t3627297)

**Comment by sourabhtk37** [comment]
Lovely. Thanks for the talk proposal @LordArcadius

**Comment by LordArcadius** [comment]
It's my pleasure 😀

**Comment by sourabhtk37** [comment]
@MSF-Jarvis any pointers or tips that can be added for this talk?

**Comment by LordArcadius** [comment]
@MSF-Jarvis you also coming mate?😎 If yes then Dayum it will be great.

**Comment by MSF-Jarvis** [comment]
When is it haha I'll see if I can show up. As far as content goes it looks kinda bland but we can talk about that back in the telegram chat.

**Comment by LordArcadius** [comment]
Oh sure!

**Comment by Manas-kashyap** [comment]
Can you give this talk on 6 January meetup.

**Comment by sourabhtk37** [comment]
It was a great IMO. Apart from internet, connectivity issues(which is given case almost everywhere), It went well. 
Looking forward to see more.
Please upload any slides relating to this talk so we can keep a log.

**Comment by sourabhtk37** [comment]
Closing this as complete.  Although still waiting for slides and resources to add in logs. @LordArcadius Please share the slides and accompanying slides for this talk for logs.

**Comment by LordArcadius** [comment]
Sorry for the delay in my reply. So here are some important things related to android kernel compilation. I am also including the PPT slides I used in talk.

Guide to compile the kernel:- 

- Clone the kernel source code of your device.
- Clone the toolchain (Check below for toolchain links)
- cd to kernel source directory
- Now we have to export our toolchain to Makefile. For that enter following commands:-
     1. **export ARCH=arm64** for 64bit devices and **export ARCH=arm** for 32bit devices.
     2. **export SUBARCH=arm64** for 64bit devices and **export SUBARCH=arm** for 32bit devices.
     3. **export CROSS_COMPILE={your toolchain path without brackets}**
            example:- **export CROSS_COMPILE=/home/lordarcadius/aarch64-linaro-linux-android/bin/aarch64-linaro-linux-android-**
- Now we will make our defconfig file. For this we must know our devices code name. In my case I am using a Redmi Note 4 and its code name is mido. You will have to find the device code on your own. Now you will have to find your defconfig file. For 64bit devices you will find it in **arch/arm64/configs** and for 32 bit you will find it in **arch/arm/config**. The defconfig name will be like device_defconfig. For my Redmi note 4 it is mido_defconfig. Now you know your defconfig file so run **make device_defconfig**. Replace device with your device code. For me it will be like **make mido_defconfig**.

- Now we will start compilation. Just enter make and wait till the compilation gets finish.
- After compilation you will find your output for 64 devices in **arch/arm64/boo**t and the file name should be **Image.gz-dtb** and for 32 bit it will be **arch/arm/boot** and file name should be **zImage**.
- Use **anykernel2** to make a flashable zip of your kernel or find zip file of any other existing kernel of your device and now you can flash it.

XDA Reference guide:- https://forum.xda-developers.com/android/software-hacking/reference-how-to-compile-android-kernel-t3627297
Help and support Telegram group:- http://t.me/LinuxKernelChat
Upstreaming guide:- https://forum.xda-developers.com/android/software-hacking/reference-how-to-upstream-android-kernel-t3626913
Toolchain:-
GCC 4.9 for 64 bit:- https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/
GCC 4.9 for 32 bit:- https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/

My Telegram username:- @lordarcadius

Thanks! I hope everything is clear and you will be now able to compile your own custom kernel.


[Android Kernel Compilation.pptx](https://github.com/ILUGD/talks/files/1638124/Android.Kernel.Compilation.pptx)
