### ISSUE TITLE
Handson on Debian packaging of nodejs modules .

### ISSUE THREAD

**Issue by Manas-kashyap** [ILUGD/talks#70]
It will be a Hands-on to pack some small modules of nodejs for Debian, I will also cover some tools like  npm2deb and other tools like lintian , and fixing some patches using Quilt . 
        
**Expected Duration**
   1hr to 1:30 hr

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner

**Pre-requisite**
   	Laptop with Debian sid in the docker.
        good internet connection.
        

  

  
[Debian_packaging.pdf](https://github.com/ILUGD/talks/files/1699672/Debian_packaging.pdf)

**Comment by sourabhtk37** [comment]
Looking forward, please properly device the talk and divide into segments so it helps in following.

**Comment by rajudev** [comment]
Closing this as it has been delivered at the meetup on 24 March 2018
