### ISSUE TITLE
Getting started with tmux and vim

### ISSUE THREAD

**Issue by vabhishek-me** [ILUGD/talks#71]
**Abstract**

 - tmux is used to multiplex several terminals allowing multiple separate terminal sessions inside a single terminal window or remote terminal session. It's very helpful in development and remote terminal sessions/coding. It is useful for dealing with multiple programs from a command-line interface, and for separating programs from the Unix shell that started the program.

 - vim is a powerful and highly configurable text editor that makes you code very fast.

*Topics*

## TMUX
  - Introduction to tmux
  - Installation
  - Exploring the features
  - Configuring to make it more personalized
  - Installing Powerline & Customizing Tmux Status Bar
  - Logging into a server and playing with attaching/deattaching

## VIM
  - Introduction to VIM
  - Basic features of VIM
  - Working with Pathogen Package manager
  - Installing plugins for VIM
  - Guidance to learn more
        
**Expected Duration**
  45 mins - 1hr

**Track**
    	- Beginner
 
**Pre-requisite**
  - Any Linux OS (Ubuntu preferred) or macOS (If windows, install some emulator or ubuntu in VM)
  - Good Internet Connection

**Resources**
  [tmux](https://robots.thoughtbot.com/a-tmux-crash-course)
  [VIM](https://scotch.io/tutorials/getting-started-with-vim-an-interactive-guide)

**Slides**
https://github.com/vabhishek-me/talks/blob/master/tmux-vim-ilugd/Getting%20Started%20With%20tmux%20and%20vim.pdf

**Comment by sourabhtk37** [comment]
@mfrw Can you suggest topics that @iammrdollar can append to existing proposal for vim?

**Comment by iammrdollar** [comment]
@sourabhtk37 I've added some topics. Will be adding more points as I go through the flow which I'm gonna follow in the talk.

**Comment by sourabhtk37** [comment]
Closing this as complete.

**Comment by mfrw** [comment]
Sorry missed it :(

**Comment by philo-math** [comment]
@vabhishek-me will you be available for our next meetup on 30th June 2018 or 1st July 2018?

**Comment by hellozee** [comment]
@vabhishek-me will you be available on 11th August for delivering this talk?

**Comment by yashwithgm** [comment]
Practical Vim is a good book for learning vim.

**Comment by vabhishek-me** [comment]
@yashwithgm Yup. In-fact its the best book.

**Comment by mfrw** [comment]
[A byte of Vim](http://files.swaroopch.com/vim/byte_of_vim_v051.pdf) by Swaroop C H, is also a very concise book that can be used a gentle introduction to vim.

**Comment by vabhishek-me** [comment]
Access Talk Contents Here: https://github.com/vabhishek-me/talks/tree/master/tmux-vim-ilugd

Closing the issue!
