### ISSUE TITLE
An Introduction to Portage Package Management System

### ISSUE THREAD

**Issue by hellozee** [ILUGD/talks#72]
**Abstract**
	Portage, the package manager of Gentoo, is quite different than other package managers. The talk will 
        about package managers in linux and what makes Portage different and more advanced than other 
        package managers like apt, yum, pacman.
        
**Expected Duration**
        30 - 40 mins

**Track**
         Intermediate

**Pre-requisite**
   	A basic understanding of the linux system, what are packages and experience of working with at least
        a single package manager.
        
**Resources**
        Portage wiki: https://wiki.gentoo.org/wiki/Portage
        Gentoo USE flags: Wiki and List of flags

**Slides**
        https://github.com/hellozee/Portage-PMS

**Comment by rajudev** [comment]
Closing as delivered at the meetup on 24 March 2018
