### ISSUE TITLE
Managing dotfiles across multiple systems

### ISSUE THREAD

**Issue by ankitrgadiya** [ILUGD/talks#73]
**Abstract**

Dotfiles are often used to configure various software, but they tend to get very messy
and hard to manage, specially across multiple systems if done by hand. So, this talk is going to be about managing dotfiles using commonly available tools like `git`, and symlinks.
        
**Expected Duration**
 
Around 20 minutes

**Track**
Beginner

**Pre-requisite**
* General knowledge about using shell
* Familiarity with `git` will be helpful though not required

**Resources**
    Don't have one yet

**Slides**
    Not ready yet

**Comment by sourabhtk37** [comment]
Can you share your availability for 14th of April?

**Comment by ankitrgadiya** [comment]
Hey, I don't actually live in Delhi so I'll have check if I can come on 14th.

**Comment by sourabhtk37** [comment]
It's okay. Don't be sorry. Let us know when you plan to visit Delhi, we will put up your talk then. Sounds good?

**Comment by ankitrgadiya** [comment]
Yeah sure. Thanks

**Comment by hellozee** [comment]
@ankitrgadiya Are you available for 6th May?

**Comment by mfrw** [comment]
@ankitrgadiya @sourabhtk37 
Although using symlinks is what majority of people use, I would _suggest_ having a go at `git --bare` repositories.
Have a look at this hackernews thread:

https://news.ycombinator.com/item?id=11070797

& this too

https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/

**Comment by cocoa1231** [comment]
Hey @ankitrgadiya 

Would you be available to present your talk on 12th May?

**Comment by philo-math** [comment]
@ankitrgadiya  will you be available for our next meetup on 30th June 2018 or 1st July 2018?

**Comment by hellozee** [comment]
@ankitrgadiya will you be available on 11th August for delivering this talk?

**Comment by hellozee** [comment]
@ankitrgadiya will you be available on 8th September?

**Comment by hellozee** [comment]
@ankitrgadiya will you be available for November 25th?

**Comment by hellozee** [comment]
closing issue due to no response from the speaker, :)
