### ISSUE TITLE
Making docker work

### ISSUE THREAD

**Issue by jayant7k** [ILUGD/talks#76]
**Abstract**
  - Basics of docker
  - What is the problem that docker solves ?
  - Workshop
     - Creating docker file
     - Running a container
     - Mounting code in container
     - Communication between containers
  - What are immutable containers ?
  - Problems with containers
  - How Kubernetes helps
  - Kubernetes architecture
  - Use case of Docker & Kubernetes	
        
**Expected Duration**
    40 min

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner        

**Pre-requisite**
   	Basic linux knowledge
        Docker installed on your laptop
        - https://docs.docker.com/install/
        Redis installation
        - apt-get install redis-server
        Docker compose
        - https://docs.docker.com/compose/install/#install-compose
        
        
**Resources**
https://www.docker.com/

**Slides**
    [slides](https://docs.google.com/presentation/d/1WbM79JFCovsbGsW-cWKS7JnI9BwzoZ3BsTiPRsRanZE/edit?usp=sharing)
    [code](https://github.com/jayant7k/dockerWorkshop.git)

    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by sourabhtk37** [comment]
Thanks for the proposal @jayant7k 
We had a similar talk before at the meetup, here's the [slides](https://github.com/mfrw/talks/blob/master/docker-intro/docker-intro.pdf)

@mfrw Can you suggest some refinement to the content?

**Comment by sourabhtk37** [comment]
Please also state your availability for 14th of April @jayant7k 
The meetup will be happening from 11am-6pm.

**Comment by sourabhtk37** [comment]
Thats okay. The audience have changed quite a lot and this would be more relevant now.

What I would suggest is make this a bit more hands-on session. Let us know.

**Comment by mfrw** [comment]
Making things handson always helps.

**Comment by jayant7k** [comment]
@sourabhtk37 @mfrw Thanks for your support. Let me prepare the content. I will share the slides by tomorrow. I will try to introduce a handson session as well.

**Comment by sourabhtk37** [comment]
That's good to hear. Please let us know if you would be able to deliver this talk/workshop on 14th of April.

**Comment by jayant7k** [comment]
Yes I will deliver it on 14th April.

**Comment by sourabhtk37** [comment]
@jayant7k Since this would require more time, shifting to this to the next meetup as we ran out of slots for meetup of 14th of April. Thanks.

**Comment by jayant7k** [comment]
@sourabhtk37, I have updated the Abstract of the talk. Moving the talk to the next meeting will help me prepare the workshop better. Thanks for that. Let me know if there is anything else that you would want me to include in the talk / workshop.

**Comment by hellozee** [comment]
@jayant7k  Are you available for 6th May?

**Comment by jayant7k** [comment]
Yes, I am available for 6th May

**Comment by hellozee** [comment]
@jayant7k could you shift to 5th May? Due to unavailability of venue for 6th we shifting out meetup to 5th.
Sorry for the inconvenience.

**Comment by jayant7k** [comment]
@hellozee yes 5th would also work for me. Can you tell me my slot, so I can plan accordingly ?

**Comment by hellozee** [comment]
@jayant7k thanks, you can check the schedule here, https://public.etherpad-mozilla.org/p/ilugd-5th-may , after the second talk is finalized we will upload the schedule to our meetup.com page

**Comment by hellozee** [comment]
@jayant7k sorry to inform, due to unavailability of a second session we have to cancel this week's meetup.

**Comment by sourabhtk37** [comment]
@jayant7k We have moved the meetup to 12th of May. Will you be available to deliver the talk/workshop for the same?

**Comment by jayant7k** [comment]
Yes, I will be available on 12th

**Comment by sourabhtk37** [comment]
https://www.meetup.com/ilugdelhi/events/rjnzmpyxhbqb/

@jayant7k Schedule and venue is update here. I would encourage you to test your setup(projector and your laptop) before the workshop so that there is no problems with the session.

**Comment by sourabhtk37** [comment]
@jayant7k Thank you for the talk. Looking forward to hear more from you.
