### ISSUE TITLE
Debugging using Strace

### ISSUE THREAD

**Issue by mukgupta** [ILUGD/talks#77]
**Abstract**
I'll be discussing how can you debug linux processes using Strace. Will cover common linux system calls, useful strace one-liners and different scenarios where you can use strace for debugging.
            
**Expected Duration**
    30 minutes.

**Track**
      - Intermediate

**Pre-requisite**
    Linux Fundamentals 

**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    *[Slides](https://docs.google.com/presentation/d/1pun8wEFlPFu4YtZ1a9b-rMZMlfHu4ByJkZ5Y9BINmoY/edit)    
   *[Tutorial](https://github.com/mukgupta/debug-tools/tree/master/strace)
---

**Comment by sourabhtk37** [comment]
Thanks for the proposal @mukgupta 
Will you be available on 14th of April to take up this talk? Please let us know.

**Comment by mukgupta** [comment]
@sourabhtk37 : I think I can make it. What's the venue for the talk?

**Comment by sourabhtk37** [comment]
It is Investopad Gurugoan.
Can we finalise this talk for 14th of April?

**Comment by mukgupta** [comment]
@sourabhtk37 : Sure.

**Comment by sourabhtk37** [comment]
Awesome. Putting this talk on schedule then.

**Comment by sourabhtk37** [comment]
Schedule is updated [here](https://www.meetup.com/ilugdelhi/events/rjnzmpyxjbdb/).

**Comment by sourabhtk37** [comment]
Thanks for the amazing talk.
