### ISSUE TITLE
Introductions to LKMs and ftrace

### ISSUE THREAD

**Issue by cocoa1231** [ILUGD/talks#78]
**Abstract**
This talk will be a simple introduction to Loadable kernel modules, and seeing how they work and debugging them using ftrace. The audience is encouraged to participate and follow along. I will first show how to create a hello world module and inserting it. Then we'll see how to trace it and if we have the time, we will also create a device driver and ftrace that too!
        
**Expected Duration**
45 to 60 minutes

**Track**
Intermediate

**Pre-requisite**

* Software pre requisite:
    * Install the appropriate header files for your kernel. (Debian users do `sudo apt install linux-headers-$(uname -r)`
* Conceptual pre-requisites:
    * Basic knowledge of the C Programming language. Nothing too heavy
    * Being fluent with the UNIX Shell
        
**Resources**
    * This talk is heavily derived from [Derek Molloy's tutorials](http://derekmolloy.ie/writing-a-linux-kernel-module-part-1-introduction/)
    * The guy who made ftrace, Steven Rostedt has [a talk](https://www.youtube.com/watch?v=2ff-7UTg5rE) on the same, which is fantastic-ally complicated.
    
**Slides**
No slides.

**Comment by sourabhtk37** [comment]
Finalising this for 14th of April's meetup.

**Comment by cocoa1231** [comment]
@sourabhtk37 You can close this and mark it as delivered
