### ISSUE TITLE
How are buttons drawn on the screen?

### ISSUE THREAD

**Issue by hellozee** [ILUGD/talks#79]
**Abstract**
We all at some point of time wonder how do this cute little icons were drawn on the screen. The talk will                  be based on how different GUI llibrary/framework/toolkit interact with the display server through the X11 protocol to draw stuff on the screen and manage the events.  
        
**Expected Duration**
 - 30 mins

**Track**
 - Intermediate

**Pre-requisite**
 - Basic understanding of C
 - Having worked with any GUI library/framework/toolkit would be a plus
        
**Resources**
 - https://www.x.org/wiki/Documentation/
 - https://www.x.org/wiki/ProgrammingDocumentation/
 - https://www.x.org/wiki/guide/
 - https://www.x.org/releases/X11R7.5/doc/x11proto/proto.pdf

**Slides**
 - https://github.com/hellozee/talks/blob/master/x11/x11.slide

**Comment by cocoa1231** [comment]
Hey @hellozee!

Could you give this talk on June 9th?

**Comment by hellozee** [comment]
Sorry I will not be available till 10th of July.

**Comment by cocoa1231** [comment]
Okay. Thanks for letting me know
