### ISSUE TITLE
Plymouth 101 : Bootloader's Frontend

### ISSUE THREAD

**Issue by vipulgupta2048** [ILUGD/talks#80]
**Abstract**
I love to customize my system (Using Linux). I am sure other programmers think, want or love to customize their system, their own special way that their cynical mind could call their own. People customize everything, but sometimes they ignore the thing that arrives at the beginning of the system boot. That is PLYMOUTH, an archaic package running in the background way before anything in the system get loaded to present to you that splash screen/ boot up screen every-time you open your Linux distro. I will give a small talk on Plymouth and how to tweak it to your preference. 

**Expected Duration**
   30 minutes

**Track**
   	- Beginner
        
**Pre-requisite**
   	Familiarity with Linux distro.

**Resources**
    N/A

**Slides**
    Uploading soon

**Comment by cocoa1231** [comment]
Hi @vipulgupta2048!

Would you be available to give this talk on June 9th?

**Comment by vipulgupta2048** [comment]
I haven't prepared the slides yet + my evaluation would be coming up at that time. I would probably be ready in the next one.

**Comment by cocoa1231** [comment]
Okay. No problem :)

**Comment by philo-math** [comment]
Hey @vipulgupta2048, would you be available to give the talk on our next meetup probably on 30th June or 1st July?

**Comment by vipulgupta2048** [comment]
I am going out of town for that week, setbto return on the 6th. Sorry.

**Comment by philo-math** [comment]
No worries :)
Can we schedule you for our next meetup (dates yet TBD, mostly in the end of July 2018)?

**Comment by vipulgupta2048** [comment]
@philo-math I usually don't have much to do but can't confirm. I will inform on the Telegram group when I am free.

**Comment by philo-math** [comment]
@vipulgupta2048 Sure :)

**Comment by hellozee** [comment]
@vipulgupta2048 will you be available on 11th August for delivering this talk?

**Comment by hellozee** [comment]
@vipulgupta2048 will you be available on 8th September?

**Comment by vipulgupta2048** [comment]
**Slides** - https://slides.com/vipulgupta2048/vplymouth/
