### ISSUE TITLE
Swupdate: A new generation embedded linux updater

### ISSUE THREAD

**Issue by mysticTot** [ILUGD/talks#81]
**Abstract**
   SWUpdate provides a reliable way to update the software on an embedded system

**Expected Duration**
  50 Minutes (30 Minutes + 20 Minutes Demo)

**Track**
    	- Beginner
        - Intermediate

**Pre-requisite**
   	Eagerness to learn along with some introductory knowledge of :
        - [U-Boot](https://www.denx.de/wiki/U-Boot)
        - [U-Boot Env](https://www.denx.de/wiki/DULG/UBootEnvVariables)
        - [Buildroot](https://buildroot.org/downloads/manual/manual.html)
        - [cpio archive](https://en.wikipedia.org/wiki/Cpio)
        - [Yocto Project](https://www.yoctoproject.org/about/)
     
**Resources**
   [Docs](http://sbabic.github.io/swupdate)

**Slides**
    Yet to be made

**Comment by cocoa1231** [comment]
Hi @mysticTot!

Would you be available to give this talk on the June 9th meetup?

**Comment by cocoa1231** [comment]
That date isn't decided yet. I'll let you know as I find out

**Comment by philo-math** [comment]
@mysticTot  will you be available for our next meetup on 30th June 2018 or 1st July 2018?

**Comment by philo-math** [comment]
@sourabhtk37 Please close this issue as the talk has been delivered :)
