### ISSUE TITLE
The Raspberry Pi BootCamp - a series of workshops

### ISSUE THREAD

**Issue by rajudev** [ILUGD/talks#87]
**Abstract**
    This would be a hands-on workshop which will introduce you to a Raspberry Pi and making your own projects on top of it. It would cover the following contents. 
*    Introduction
*    What do I need to get started ?
*    Raspberry Pi system specifications
*    Ports, Pins and their uses
*    Raspberry Pi with Raspian OS
*    Setting Up Rasbian OS and the initial user configuration
*    “Hello World” Programming on Raspberry Pi
*    Interfacing electronics with the Raspberry Pi
     * LEDs
     * Motors
     * Sensors
     * Small projects
* Using Raspberry Pi as a computer
* Advanced configurations
* Wrapping up. 
        
**Expected Duration**
5 hours

**Track**
   	Beginner

**Pre-requisite**
A good overview of Linux would be helpful.
        
**Resources**
Will be added after the workshop

**Slides**
    Links to the slides.

**Comment by hellozee** [comment]
Lets plan a `PiJam` for our next meetup then

**Comment by rajudev** [comment]
@hellozee you were not there when we had a meetup with RPi's at Innov8 in CP. That was amazing as well. 
I think along with this we could have a meetup in that style/pattern as well

**Comment by hellozee** [comment]
@rajudev don't worry, I have gone through the album, we can plan the next meetup accordingly, I would propose something like a talk on first session then people implement it on their pis in the second session

**Comment by tanmaymohan** [comment]
How different it will be from the Rpi Birthday JAM ?

I attended it and now I am thinking if I could contribute as well somehow

**Comment by rajudev** [comment]
This would be a lot different. Although I did not got to attend the Raspberry Pi Jam, I did got to hear a lot about it. 
This would be traditional hands-on walk through with the Raspberry Pi / SBC, its details and how to go about making/creating different types of projects with them. You are surely welcome to contribute in anyway you can.

**Comment by rajudev** [comment]
I think we delivered most of the content stated in the issue here and a lot more in the RPi JAM workshop series that we did. So I guess, we can close this one.
