### ISSUE TITLE
Bootstrapping a Civilization?

### ISSUE THREAD

**Issue by radamar** [ILUGD/talks#88]
Building a civilization from scratch?

1. Why?
Capitalism is going terribly wrong. Destroying our planet. People are unhappy with their lives.

2. We want a free society. Where people respect and trust each other.
We cannot have a free society if the only way to earn a living is to write proprietary software, which is unethical. Similarly, non-programmers should also have freedom to make professional choices.

3. The problem.
Building a free civilization on a bare piece of land. From scratch! Free for all, not just the rich.

4. The analogy.
The problem is analogous to the bootstrapping problem, building a system without putting trust in binaries. Instead of the system we have a civilization and instead of binaries we have money, which cannot be trusted!

5. Food
Someone will have to come up with a great technological solution. Possible solutions: hydroponics?

6. Water
Again, lots of work to be done! Possible clues: Gerald Pollack 4th State of Water!

7. Shelter
Work being done. Buckminster fuller was the first to imagine and build concept of a resource efficient and self sufficient house.

8. Energy
Solar power is very expensive to tap!

9. Free hardware and software will help us get there.
Free and open source software is already enriching the lives of those who use it. But there is much more to be done! Free Designs, 3D printing, RISCV.
        
Expected Duration
    30 minutes

Pre-requisite
   FOSS ideals
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by miphilomath** [comment]
@radamar will you be available to take an online session in upcoming week?

**Comment by o-nly** [comment]
Hi, I am the author of the post. I had setup 2FA(2 factor authentication) on the author account and lost the 2FA device unfortunately.

> @radamar will you be available to take an online session in upcoming week?
yes :)

Thanks

**Comment by miphilomath** [comment]
@o-nly 

Great, when can we schedule the session? The session will be streamed on Jitsi and live streamed on Youtube. Here is the [calendar ][1] for the upcoming scheduled sessions. Please share the available date and time for the session. For available dates, please check the calendar.

[1]: https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

**Comment by o-nly** [comment]
> Great, when can we schedule the session? 

9pm-10pm on 16th of this month looks good to me. Otherwise, if that is taken by the time, then 18th same time.

I'll try to send in the slides ahead of time.

Thanks :)

**Comment by miphilomath** [comment]
We scheduled your talk on 18th April, 2020 at 9PM IST. Here is the calendar [link] to the virtual meetups we have planned. Please connect with us via GitHub, twitter or telegram to co-ordinate. 

[1]: https://calendar.google.com/calendar/embed?src=fnmnnmekvtfj986tse2il0al50%40group.calendar.google.com&ctz=Asia%2FKolkata

Please share your slides and intro either here or on our telegram channel.

**Comment by o-nly** [comment]
I saw the schedule, thanks.

> Please connect with us via GitHub, twitter or telegram to co-ordinate.
> Please share your slides and intro either here or on our telegram channel.

Roger that :)

**Comment by miphilomath** [comment]
Ping @o-nly. Can your share your contact details to get in touch with you? Or please get in touch with us on telegram or on our mailing list. http://frodo.hserus.net/mailman/listinfo/ilugd

**Comment by o-nly** [comment]
slides.
[bootstrap.pdf](https://github.com/ILUGD/talks/files/4497379/bootstrap.pdf)

**Comment by miphilomath** [comment]
Talk is delivered on April 18, 2020. Link to the recording: https://www.youtube.com/watch?v=_c0Ww42UQE0
