### ISSUE TITLE
Modern JavaScript Packaging

### ISSUE THREAD

**Issue by ramantehlan** [ILUGD/talks#89]
**Abstract**

In 2020, [Github bought NPM](https://blog.npmjs.org/post/612764866888007680/next-phase-montage), and In 2019, [Github also announced its Package registry](https://techcrunch.com/2019/05/10/github-gets-a-package-registry/) for Javascript and few other languages, which means now you can publish and manage your packages on both Github and NPM and use any package manager client. Through this talk, I will try to explain how you can do it, and **by the end, you will know everything to build and publish your package to any registry, Github, or NPM.** 

**Expected Duration**: 40 - 60 Minutes

**Track**: Beginner

**Pre-requisite**: Basic Programming experience.

**Resources**
- [Blog on Modern Javascript Packaging](https://ramantehlan.github.io/blog/post/2020/modern-javascript-packaging/)

**Slides**
    `Will be updated later`

**Comment by hellozee** [comment]
@ramantehlan will you be available for November 25th?

**Comment by miphilomath** [comment]
The talk is scheduled on 19th April, 2020 at 2100 on Jitsi

**Comment by miphilomath** [comment]
Delivered on April 19, 2020. Link to the recording: https://www.youtube.com/watch?v=1aV1uM64rk4
