### ISSUE TITLE
Let's talk some non tech essential things?

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/talks#93]
**Abstract**
1. Campus to Corporate
2. Automating boring stuff at workplace
3. Indian taxation on Income
4. Investment for Beginners
5. Staying motivated with work
6. Finding new challenges and much more
  
**Expected Duration**
    30 mins

**Track**
    	- Beginner

**Pre-requisite**
N/A
        
**Resources**

**Slides**
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by hellozee** [comment]
@iayanpahwa will you be available for November 25th?

**Comment by iayanpahwa** [comment]
@hellozee I would like to put this one on hold for some time. You can either keep it open or close so I can re-open again when there is right time for this one.

**Comment by rajudev** [comment]
@iayanpahwa I gues you delivered this one. and you did it very well. Should I close this one?
