### ISSUE TITLE
Let's do, Git Stash!

### ISSUE THREAD

**Issue by mridubhatnagar** [ILUGD/talks#95]
**Abstract**
	Provide a brief introduction about the talk.
    Also list the topics that the talk is going to cover.
        
**Expected Duration**
    Approximate duration of the talk.

**Track**
   	ILUG-D talks are divided intro three tracks:
    	- Beginner
        - Intermediate
        - Advanced

**Pre-requisite**
   	Enlist here if there are any pre-requisite for attending the talk.
        
**Resources**
    Links to resources related to the talk and from where one can 
    read up on the same.

**Slides**
    Links to the slides.
    
---
### Note
Please do add/upload slides in pdf or an open document format.
People who are using LibreOffice, openOffice etc. should not have any problems viewing it.

**Comment by mridubhatnagar** [comment]
I shall be updating this by tomorrow evening. Planning around the lines mentioned in this blog post. 
https://medium.com/@mridubhatnagar/tech-git-stash-fcd7fe67e3f5

**Comment by rajudev** [comment]
@mridubhatnagar will you be available to take this talk in the next meetup? Dates not decided yet.

**Comment by mridubhatnagar** [comment]
@rajudev yes sure. Though I won't be there on 30-31st March weekend. And 13-14th April weekend. Any weekend other than the mentioned one works fine for me.

**Comment by taskmaster9001** [comment]
please update the issue description, @mridubhatnagar

**Comment by taskmaster9001** [comment]
looking forward to the session! ^_^

**Comment by miphilomath** [comment]
Delivered on April 13, 2020. Link to youtube recording: https://www.youtube.com/watch?v=jFjngXh7yew
