### ISSUE TITLE
Approaching Modern C++, something you weren't taught at school

### ISSUE THREAD

**Issue by hellozee** [ILUGD/talks#98]
**Abstract**
    I go over the new stuff introduced in C++11, C++14,  C++17 & somewhat C++20 also and 
    show how writing C++ can be less painful and as easy as Python if not easier.
        
**Expected Duration**
    30 Minutes

**Track**
        - Intermediate

**Pre-requisite**
    A basic idea of working with C++ and OOP
        
**Resources**
    https://github.com/AnthonyCalandra/modern-cpp-features
    https://en.wikipedia.org/wiki/C%2B%2B11
    https://en.wikipedia.org/wiki/C%2B%2B14
    https://en.wikipedia.org/wiki/C%2B%2B17
    https://en.wikipedia.org/wiki/C%2B%2B20

**Slides**
    [WIP]

**Comment by shubhra-agrawal** [comment]
@hellozee That's a great topic for C++ developers and I would like to attend. Is there an expected date for this talk?

**Comment by hellozee** [comment]
@shubhra-agrawal not at the moment

**Comment by hellozee** [comment]
Attaching the slides (uses libreoffice impress) and the source code that I showed, :smile: 
[cpp talk.tar.gz](https://github.com/ILUGD/talks/files/4640668/cpp.talk.tar.gz)
